### ISSUE TITLE
New setup_requires

### ISSUE THREAD

**Issue by williamjamir** [pyexcel/pyexcel#105]
Hello,

With the new release the setup.py now requires installing 'gease'. 

I didn't understand this requirement, for what I understood this package is a command line interface for make releases, am I right?

**Comment by chfw** [comment]
Hmm... for publishing, it uses gease, which make my life easier as all commands are integrated but I can see it causes some problem for the end user as gease is of no use if not the maintainer. Let me look into this.

**Comment by chfw** [comment]
the integration equals:

python setup.py publish = python setup.py sdist bdist_wheel upad -r pypi + github release this version

**Comment by williamjamir** [comment]
Just giving some background information, I'm including the pyexcel-* packages on conda-forge to be installed with conda, so I need to build the package to be able to include in the repository. 

So my point is, the package gease doesn't look like a real build dependency for pyexcel, even though it makes the life of the maintainer easier.
Could you perhaps install this package separately, without enforcing dependencies in the package?

**Comment by chfw** [comment]
OK. I will remove it from setup require and make gease as optional in setup.py. with or without it, setup.py will function.
