### ISSUE TITLE
pyexcel not writing column names to xlsx

### ISSUE THREAD

**Issue by jakedotio** [pyexcel/pyexcel#110]
I'm using pyexcel to manipulate a TSV format file and re-save it as XLSX after removing some columns.

This works as expected, preserving column names (as the first row):

```
import pyexcel as pe
records = pe.get_sheet(file_type='tsv', file_content=report)
pe.save_as(array=records, dest_file_name='report.xlsx')
```

After removing columns however, the records object is correct, but when saving column names aren't saved to the XLSX file:

```
import pyexcel as pe
records = pe.get_sheet(file_type='tsv', file_content=report, name_columns_by_row=0)
del records.column['column-name-1','column-name-3']
pe.save_as(array=records, dest_file_name='report.xlsx')
```

Any ideas?

**Comment by chfw** [comment]
name_columns_by_row affects column names, which is taken out from its content array. And the default iterator for sheet is .rows() , which only looks at content array. The fix is to call records.to_array() in later call.

**Comment by jakedotio** [comment]
Thank you!
