### ISSUE TITLE
[Question] Is there a `get_data` function in pyexcel similar to those found in pyexcel-xls and pyexcel-xlsx

### ISSUE THREAD

**Issue by simkimsia** [pyexcel/pyexcel#111]
I have an issue.

I have a working code that will use  `get_data` function from `pyexcel-xls`

Now I may have to perform the same feature on xlsx file.

Instead of writing a duplicate code or code that checks the filetype, is there a way I can simply call `get_data` using pyexcel and let pyexcel decide whether to use `pyexcel-xls` or `pyexcel-xlsx`?

**Comment by chfw** [comment]
yes and no. 

Yes, there is a corresponding function and it is get_book_dict(). There are [other functions](http://pyexcel.readthedocs.io/en/latest/capability.html) for you to choose too. And before you take it away, there exists `get_data` function from pyexcel_io too. It should automatically also choose a plugin according to its file extension. 

No when you need to detect merged cells. I have not yet ported the same feature to pyexcel-xlsx yet. According to openpyxl's documentation , it is possible but I will need to implement it a bit later. Then, no blockers.

Let's supposed the feature have been implemented in pyexcel-xlsx, there is a minor detail you will need to pay attention to. It is the fact that although pyexcel-xls does not support merged_cells on xlsx, it does read xlsx too. So with pyexcel-xls and pyexcel-xlsx installed in the same environment, both would compete for the `reading` job, so an extra parameter is needed in this case: `library='pyexcel-xlsx'` , which means pyexcel-xlsx is nominated the function call for your xslx file. And this `library` parameter is accepted in both libraries: pyexcel and pyexcel-io.

**Comment by chfw** [comment]
please install pyexcel-xlsx=0.5.5

**Comment by simkimsia** [comment]
Sorry I just saw this. Let me paste my current code so that you have an idea what i am trying to do.

```python
      if view.view_type == 'xls':
            data = pyexcel_xls.get_data(options['path'],
                                        start_row=start_row,
                                        row_limit=row_limit,
                                        skip_hidden_row_and_column=True)

        if view.view_type == 'xlsx':
            data = pyexcel_xlsx.get_data(options['path'],
                                         start_row=start_row,
                                         row_limit=row_limit,
                                         skip_hidden_row_and_column=True)

```

I am hoping to avoid writing this in two if blocks. It's a minor thing.

**Comment by chfw** [comment]
yes, there is an easy way.

```
# import pyexcel_xls
# import pyexcel_xlsx
from pyexcel_io import get_data

data = get_data(options['path'],
    start_row=start_row,
    row_limit=row_limit,
    skip_hidden_row_and_column=True)
```

And I suppose you are reading a sheet from a excel book, so equivalent code from pyexcel is:

```
from pyexcel import iget_array

data_generator = iget_array(options['path'],
    start_row=start_row,
    row_limit=row_limit,
    skip_hidden_row_and_column=True)
for row in data_generator:
     for cell in row:
             print(cell)
```

**Comment by simkimsia** [comment]
1. is there an equivalent docs like https://pyexcel.readthedocs.io/en/latest/ for pyexcel-io? I don't mind helping you build it out or fill it in. Writing documentation helps me get better with source code.
2. you gave me two options. which one is better? and again, can i contribute to the documentation for `iget_array`?

**Comment by chfw** [comment]
Here is equivalent docs for pyexcel-io: http://pyexcel-io.readthedocs.io/en/latest/

As for iget_array, it returns you a 2-dimensional array instead of a dictionary and by default it is the first sheet.

To get all sheets from pyexcel, you do get_bookdict() instead.
