### ISSUE TITLE
isave_as not writing periodically for XLS and XLSX formats

### ISSUE THREAD

**Issue by PLPeeters** [pyexcel/pyexcel#112]
I'm using `isave_as` to save large datasets to files. When using the CSV format, the file is being built progressively, which makes it very memory efficient. When using XLS or XLSX, it seems to store everything in memory before dumping it to the file all at once, which requires the whole dataset to fit in memory.

I suppose it's trickier to write as you go for these formats, but I'm wondering if it would still be possible?

**Comment by chfw** [comment]
Indeed, it is trickier. The writers for xls, xlsx and ods format needs to hold data in full and in memory before writing out. Hence, csv format make itself standing out as a star in write-as-you-go style.

**Comment by chfw** [comment]
Could you step back a bit and ask why you would like to store data in xls or xlsx format? Could you have an alternative format: e.g. a database?

**Comment by PLPeeters** [comment]
I'm exporting datasets directed towards end users, most of which are using Excel and not OpenOffice or LibreOffice. Since Excel is _terrible_ at handling CSV files, exporting data to XLS or XLSX just makes more sense. It's what most users are familiar with, so it simplifies things greatly. If it wasn't for that, the CSV format would indeed be my go-to.

**Comment by chfw** [comment]
xls, xlsx or ods are zipped directory of several files. hence, it needs everything in memory for zipping operation. so far, I have not seen a writer that could flush a buffer into a zip, then continue next portion.

**Comment by PLPeeters** [comment]
I haven't researched this enough yet, so my knowledge on this exact subject is rather limited, but wouldn't it be possible to write the structure of the ZIP to a temporary folder as you go before zipping the whole thing into an XLS(X) file?

**Comment by chfw** [comment]
Hei, wait a moment. It may be the case with pyexcel-xls for writing xls. Which plugin have you used so far?

Have you tried pyexcel-xlsxw yet? Here is what it claims: http://xlsxwriter.readthedocs.io/working_with_memory.html.

And please also try pyexcel-xlsx, which has optimized xlsx writer using openpyxl.

**Comment by chfw** [comment]
Please checkout my patreon post here for writing performances: https://www.patreon.com/posts/memory-profiling-11343397

And here is another paid post on isave_as functions:
https://www.patreon.com/posts/sharp-in-memory-13152275

**Comment by PLPeeters** [comment]
Thanks, I'll go check all that out. I think I should be able to find what I need!

**Comment by PLPeeters** [comment]
I just went through everything and there's just one thing that gets me confused. Can I somehow make this work using `isave_as` or do I need to use `xlsxwriter.Workbook` directly? I tried the following line of code and it doesn't seem to make any difference:

    pyexcel.isave_as(records=data_generator, dest_file_stream=file_obj, dest_file_type='xlsx', dest_library='pyexcel-xlsxw', dest_options={'constant_memory': True})

**Comment by chfw** [comment]
That comes to the way pyexcel handles it plugin system. I guess you have both pyexcel-xlsx and pyexcel-xlsxw.

> In order to manage the list of plugins installed, you need to use pip to add or remove a plugin. When you use virtualenv, you can have different plugins per virtual environment. In the situation where you have multiple plugins that does the same thing in your environment, you need to tell pyexcel which plugin to use per function call. For example, pyexcel-ods and pyexcel-odsr, and you want to get_array to use pyexcel-odsr. You need to append get_array(…, library=’pyexcel-odsr’).

For isave_as function, you can try one of the two:

1) uninstall pyexcel-xlsx and keep only pyexcel-xlsxw
2) since the writer is used in destination part of the work, when pyexcel-xlsx and pyexcel-xlsxw co-exsit, the extra parameter in isave_as(...dest_library='pyexcel-xlsxw') will force pyexcel to use one over another.

According to the benchmark exercise that I have done last year, the difference between the two drivers might be small. The reasons are: I have configured openpyxl to use optimized driver and xlsxwriter to use constant memory.

**Comment by PLPeeters** [comment]
Thanks for the clarification, it does seem to work now. Is there any way to do the same for XLS files? I could probably remove the XLS option given XLSX works, but if I could keep it that would be great.

**Comment by PLPeeters** [comment]
I didn't notice this at first, but it actually generates corrupted XLSX files. When opening them in Excel, I get the following message:

> Excel could not open export.xlsx because some content is unreadable. Do you want to open and repair this workbook?

Repairing the file seems to work, but it should work straight out of the box... Any clues?

**Comment by chfw** [comment]
which library? pyexcel-xlsx or pyexcel-xlsxw

**Comment by PLPeeters** [comment]
pyexcel-xlsxw. I looked into it a bit and found a few issues on the XlsxWriter repo regarding that. The only reply from the developer that could maybe help is this one: https://github.com/jmcnamara/XlsxWriter/issues/484#issuecomment-350281063. Could it be that the plugin does some kind of incorrect write to the worksheet?

**Comment by chfw** [comment]
> Is there any way to do the same for XLS files? 

@PLPeeters , no, I have not found a way in xlwt to do the same.

**Comment by chfw** [comment]
@PLPeeters , do you have a reproducible and public code set? I can have a look.

**Comment by PLPeeters** [comment]
I think I just found what causes the issue with the unreadable content. It seems to happen whenever I have URLs in a workbook. Do you want me to open a new issue for this?

**Comment by chfw** [comment]
Please do so
