### ISSUE TITLE
issue with save_book_to_database(), unable to load sheets into db as models

### ISSUE THREAD

**Issue by Lrisingr** [pyexcel/pyexcel#113]
request.FILES['file'].save_book_to_database(models=[Prod, Dev, Uat], initializers=[None, None, None],
                                              mapdicts=[columns, columns, columns])
I'm trying to save the existing sheets of a xlsx file to mysql db, using the above mentioned method, the create_sheet() of DjangoBookWriter() instance raises an exception "No Django models found"

While debugging through the code, 
def get_book_stream(**keywords):
    a_source = SOURCE.get_book_source(**keywords)
    sheets = a_source.get_data()
    filename, path = a_source.get_source_info()

the method, get_data(), get_source_info(), retrieves the data from the class instance of ReadExcelFileMemory(Abstractclass) from memory_input.py of pyexcel .  

Plugins.get_source_info() returns **params.MEMORY, None**, which are predefined in  **pyexcel.plugins.sources.params.py** as "memory" as string and None respectively. May I know if the issue with django models is related to this?

**Comment by Lrisingr** [comment]
Please disregard, it was just a minor issue, my excel book has sheet names in Prod, Dev, Uat, while Django converts every model into lowercase.

**Comment by chfw** [comment]
Can I close this issue?

**Comment by chfw** [comment]
Please re-open it if it is still a problem
