### ISSUE TITLE
cell_value (matrix.py) function is slow in python2

### ISSUE THREAD

**Issue by arunkumar-ra** [pyexcel/pyexcel#114]
Line 83 in matrix.py 
`if row in self.row_range() and column in self.column_range():`
is not optimal when using python2. Membership test in xrange is very slow when the member value increases. For example try running 
`100000000 in xrange(1000000000)` vs `1 in xrange(1000000000)`

It would be faster to use 
`if row < self.number_of_rows() and column < self.number_of_columns():`

**Comment by chfw** [comment]
will release it in next maintenance fix and in v0.6.0
