### ISSUE TITLE
set print area ?

### ISSUE THREAD

**Issue by simkimsia** [pyexcel/pyexcel#116]
Happy CNY to you, my friend.

I have a question. I have tried searching the docs for pyexcel about setting print area and I cannot find it. Is it supported?

**Comment by chfw** [comment]
Thanks! The year of dog it is. Do you celebrate lunar new year? I am afraid that pyexcel does not support print area. Let me check other libraries if they have it covered.

**Comment by simkimsia** [comment]
>Do you celebrate lunar new year? 

Yes I do. :)

>I am afraid that pyexcel does not support print area. Let me check other libraries if they have it covered.

no worries

**Comment by chfw** [comment]
Great! we got something in common :). Any issues, just give me a shout!
