### ISSUE TITLE
is there a simple way to read a filepath and identify which excel file type it is?

### ISSUE THREAD

**Issue by simkimsia** [pyexcel/pyexcel#119]
Is there a simple function that I can read a filepath and identify the excel file type?

Or it's simpler to read the filename for the file extension using normal python?

e.g.

`some_function('this_is_excel.xlsx')` returns `xlsx`
`some_function('this_is_another_excel.xls')` returns `xls`

**Comment by chfw** [comment]
As of now, later method is what pyexcel use, which would fail when an xlsx file is named as 'xlsx.xls'.

**Comment by simkimsia** [comment]
I wrote my own using pathlib, so it's applicable for python 3.5 and upwards only

```
from pathlib import Path


def read_file_format(file_path='test_file.xlsx'):
    '''
    returns .xlsx or .xls
    '''
    return Path(file_path).suffix
```

I think this is good enough for me at this point.

Thanks!
