### ISSUE TITLE
i can save empty xlsx but not empty xls file

### ISSUE THREAD

**Issue by simkimsia** [pyexcel/pyexcel#120]
requirements.txt

```
pyexcel==0.5.7
pyexcel-xlsx==0.5.5
pyexcel-xls==0.5.5
```

I have a code that's like this
```

def save_empty_file(save_as_path='c71_pyexcel_empty.xlsx'):
    book = pyexcel.Book()
    book.save_as(save_as_path)
```

it works perfect with xlsx but not with xls.

I get index out of range error

![image](https://user-images.githubusercontent.com/245021/37239138-d8a09a22-2470-11e8-8f69-7cd4791b39ee.png)

I tried to follow the docs in 

http://pyexcel.readthedocs.io/en/stable/tutorial_data_conversion.html#how-to-save-an-python-array-as-an-excel-file

This works though

```
def save_empty_file_another_way(save_as_path='c71_pyexcel_empty.xlsx'):
    data = []
    pyexcel.save_as(array=data, dest_file_name=save_as_path)
```

**Comment by chfw** [comment]
I will look at empty xls using Book later today.

**Comment by chfw** [comment]
As you can see from the stack trace, xlwt assumes there is one active sheet whereas we just dont have any. With xlsx, we can create a book without any sheets. The workaround would be to provide a dummy sheet when the xls book have no sheet, but this creates an inconsistency with other libraries. Hence, the most appropriate logic is to raise an exception and accept this in-convenience. What do you think?

**Comment by simkimsia** [comment]
>Hence, the most appropriate logic is to raise an exception and accept this in-convenience. 

I agree. Good idea!
