### ISSUE TITLE
A Deprecation Warning is generated, every time I read data from an xlsx file

### ISSUE THREAD

**Issue by Sreekhar** [pyexcel/pyexcel#121]
```
@staticmethod
def read_stop_words():
        excluded_words_list = []
        stop_words_information = pyexcel_xlsx.get_data("files//StopWordsList.xlsx")
        stop_words_list = stop_words_information['WordsList']
        for count in range(1, len(stop_words_list)):
            excluded_words_list.append(stop_words_list[count][0])

        return excluded_words_list

```
I get the following error message every time I call the above function. Wouldn't effect my code in the future right?

![image](https://user-images.githubusercontent.com/14799815/37435596-4a03aa78-27ba-11e8-858e-7dabf305e94d.png)

**Comment by chfw** [comment]
well, that depends on openpyxl if they want to keep the backward compatibility. 

So, it would make more sense to change pyexcel-xlsx. Let me release another version to get rid of this warning.

**Comment by chfw** [comment]
Just came to know that we have PR here: https://github.com/pyexcel/pyexcel-xlsx/pull/24. Hence, I am closing this issue.

**Comment by chfw** [comment]
please upgrade to pyexcel-xlsx version 0.5.6
