### ISSUE TITLE
How to add a new empty sheet into xlsx?

### ISSUE THREAD

**Issue by simkimsia** [pyexcel/pyexcel#122]
I am trying to better learn pyexcel hence I am writing my own code samples.

This is my attempt to save a new empty sheet into a xlsx file

```
def add_new_sheet(file_path, new_sheet_name):
    book = pyexcel.get_book(file_name=file_path)
    if (has_sheet(file_path, new_sheet_name)):
        raise Exception
    book[new_sheet_name] = []
    return book.save_as(file_path)

## and then somewhere later I did this
new_sheet_name = 'New Sheet'
index.add_new_sheet(save_path, 'New Sheet')
```

I get attributeerror
```
>       book[new_sheet_name] = []
E       AttributeError: __setitem__
```

What's the pyexcel way to do this?

**Comment by chfw** [comment]
```
from pyexcel import Book, Sheet

b=Book()
b+=Sheet(name='new sheet')
print(b)
b+=Sheet([[1,2,3]], name='new sheet2')
print(b)
```

**Comment by simkimsia** [comment]
works.

Thank you!

**Comment by k1ngf15h3r** [comment]
> ```
> from pyexcel import Book, Sheet
> 
> b=Book()
> b+=Sheet(name='new sheet')
> print(b)
> b+=Sheet([[1,2,3]], name='new sheet2')
> print(b)
> ```

Thank you for this hint. I am trying this with an ods book but when I try to do `book.save_as(self.file)` I got this error:

```python
'builtin_function_or_method' object has no attribute 'replace'
```

any idea how to fix this?
