### ISSUE TITLE
Pyexcel with pyinstaller

### ISSUE THREAD

**Issue by ganyfml** [pyexcel/pyexcel#123]
Hi, I am trying to get pyexcel work with pyinstaller, and I continually get error:

`Please check if there were typos in function parameters: {'file_name': 'credential.xls'}. Otherwise unrecognized parameters were given.
`

I have followed the website http://pyexcel.readthedocs.io/en/latest/pyinstaller.html to include the hidden import for both pyexcel-io and pyexcel-xls but with no luck.

Any help is appreciated, thanks!

Minimal working example:
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim: set noexpandtab tabstop=2 shiftwidth=2 softtabstop=-1 fileencoding=utf-8:

from pyexcel import iget_records

credentials_raw = iget_records(file_name='credential.xls')

print(list(credentials_raw))

```

Pyinstall commend:

`pyinstaller run.py --hidden-import pyexcel_io.readers.csvr --hidden-import pyexcel_io.readers.csvz --hidden-import pyexcel_io.readers.tsv --hidden-import pyexcel_io.readers.tsvz --hidden-import pyexcel_io.writers.csvw --hidden-import pyexcel_io.readers.csvz --hidden-import pyexcel_io.readers.tsv --hidden-import pyexcel_io.readers.tsvz --hidden-import pyexcel_io.database.importers.django --hidden-import pyexcel_io.database.importers.sqlalchemy --hidden-import pyexcel_io.database.exporters.django --hidden-import pyexcel_io.database.exporters.sqlalchemy --hidden-import pyexcel_xls --hidden-import pyexcel_xls.xlsr --hidden-import pyexcel_xls.xlsw
`

Error Message:
```
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    print(list(credentials_raw))
  File "site-packages\pyexcel\core.py", line 189, in iget_records
  File "site-packages\pyexcel\internal\core.py", line 19, in get_sheet_stream
  File "site-packages\pyexcel\internal\source_plugin.py", line 76, in get_source

  File "site-packages\pyexcel\internal\source_plugin.py", line 65, in get_a_plug
in
  File "site-packages\pyexcel\internal\source_plugin.py", line 48, in load_me_no
w
  File "site-packages\pyexcel\internal\source_plugin.py", line 138, in _error_ha
ndler
pyexcel.exceptions.UnknownParameters: Please check if there were typos in functi
on parameters: {'file_name': 'credential.xls'}. Otherwise unrecognized parameter
s were given.
[3248] Failed to execute script run

```

Environment:
```
OS: Windows 7
Python: 3.5.4
pyexcel: 0.5.7
pyexcel-io: 0.5.6
```

**Comment by ganyfml** [comment]
Never mind, I forget to include the hidden import for pyexcel-io. Program working now. Thanks for the detail documentation!

Please close the case.

**Comment by chfw** [comment]
cheers! I am glad that you got your way out of it 👍
