### ISSUE TITLE
[Question] Is it correct to say that it's not so easy to copy worksheet from one workbook to another workbook using other libraries?

### ISSUE THREAD

**Issue by simkimsia** [pyexcel/pyexcel#124]
Hi there, 

I am beginning to play around with other excel libraries such as openpyxl.

And I realise that it's not as easy as pyexcel to copy a worksheet from one workbook to another. In fact to do something like that, it seems like I need to loop through all the cells in one sheet before I copy to another. 

Is that correct? And is it part of the reason why you created pyexcel?

**Comment by chfw** [comment]
copying a worksheet in python is BIG task if you use python. On the stackoverflow, there are many questions like it, ranging from xlsx, xls to ods. Other variables are: styles, charts and images. 

pyexcel stands from a web developer's perspective, how could a developer easily retrieve the data inside the excel sheets, given so many excel formats out there? In the web context, a developer mostly read the data, transform them to meet their needs and maybe import them into database too. Once the code is tested and deployed to production, to add new support for a new file format is a risky task if pyexcel is not used. Suppose the solution supports xls and xlsx, and the need to support ods emerges, new piece of code should be written using one of the libraries: odfpy, ezodf, and be tested again.

The scope of pyexcel slightly widened to take care of jupyter notebook users and tries to attract data scientists, but this is a long way to go.

**Comment by chfw** [comment]
Yes, cannot avoid two for loops. [pyexcel-xlsxr](https://github.com/pyexcel/pyexcel-xlsxr/blob/master/pyexcel_xlsxr/xlsxr.py), which does not use openpyxl, needs two for loops.

**Comment by simkimsia** [comment]
Got it thanks
