### ISSUE TITLE
How to order sheets alphabetically using pyexcel? Is this the best way to do so?

### ISSUE THREAD

**Issue by simkimsia** [pyexcel/pyexcel#125]
Hi there, 

I am writing a guide to document some of the more common commands I use with pyexcel.

For ordering sheets alphabetically I wrote this using some clues from documentation:

```
def order_sheets_alphabetically(
    file_path,
    dest_file_path,
    reverse=False
):
    book = pyexcel.get_book(file_name=file_path)
    sheet_names = book.sheet_names()
    sheet_names.sort(reverse=reverse)
    data = OrderedDict()
    for sheet_name in sheet_names:
        data.update({sheet_name: book[sheet_name]})
    return pyexcel.save_book_as(
        bookdict=data, dest_file_name=dest_file_path)
```

Is this the best way of doing so?

**Comment by chfw** [comment]
I think I could supply an additional method on Book to sort the sheet names. After that, you could book.save_as(dest_file_path).

**Comment by simkimsia** [comment]
Thanks. I presume my code is valid then.

**Comment by chfw** [comment]
```
def order_sheets_alphabetically(
    file_path,
    dest_file_path,
    reverse=False
):
    book = pyexcel.get_book(file_name=file_path)
    book.sort_sheets(reverse=reverse)
    book.save_as(dest_file_path)
```

**Comment by chfw** [comment]
`pip install https://github.com/pyexcel/pyexcel/archive/master.zip` will get the version for your trial.

**Comment by simkimsia** [comment]
oh thank you!

will try this out and let you know

**Comment by simkimsia** [comment]
okay 

0.5.8 passed
0.6.0 apparently not installable

the master branch is okay.

Thank you
