### ISSUE TITLE
didn't set sheetname when saving records

### ISSUE THREAD

**Issue by goldmonkey163com** [pyexcel/pyexcel#126]
```
import pyexcel
records=pyexcel.get_records(file_name='凭证导入模板.xls')
records.append(records[0])
pyexcel.save_as(records=records,dest_file_name='03211339.xls',dest_sheet_name='凭证')
```

I ran the code above but when I open the file I found the sheet name is 'pyexcel_sheet1'

**Comment by chfw** [comment]
Just had a look, it is true that sheet_name is not passed on. let me think about the parameters.

At the moment , `class Sheet` accepts `name` to set sheet name. `sheet_name` is felt more informative.

**Comment by chfw** [comment]
`pip install https://github.com/pyexcel/pyexcel/archive/master.zip` will get you the enhancement.
