### ISSUE TITLE
[Comment] You should put your open source on https://salt.bountysource.com/

### ISSUE THREAD

**Issue by simkimsia** [pyexcel/pyexcel#128]
I came across this website https://salt.bountysource.com/

I think it's another interesting way for you to earn a salary from your good work in pyexcel.

When I search under the keyword salt, pyexcel is not listed. You should be there. 

https://salt.bountysource.com/?search=excel

**Comment by chfw** [comment]
Thanks for the tip-off. I didn't know bountysource has a salt option before. I will sign up.

**Comment by simkimsia** [comment]
welcome
