### ISSUE TITLE
For XLSX files, iget_records seems to load the whole file in memory before it starts to return content

### ISSUE THREAD

**Issue by PLPeeters** [pyexcel/pyexcel#131]
I just tried this with a 30 MB Excel file of around 500k rows:

    with open('big_excel_file.xlsx') as f:
        sheet = pyexcel.iget_array(file_type='xlsx', file_stream=f)
        print sheet.next()

The print takes around a minute to show up, which seems unnecessarily long. It seems like it's loading the whole file in memory before it starts to yield, which shouldn't happen.

**Comment by chfw** [comment]
Have you used pyexcel-xlsxr? Otherwise it is expected behavior.

**Comment by PLPeeters** [comment]
Seems a bit counterintuitive for an iterator function that is described as being memory efficient. Can I just install it and add `library='pyexcel-xlsxr'` to the parameters or do I need to use it manually?

**Comment by chfw** [comment]
Yes, you try ' install it and add library='pyexcel-xlsxr' to the parameters'.

**Comment by chfw** [comment]
I see your point and that's why I have created pyexcel-xlsxr, pyexcel-odsr after realizing such a behaviour of pyexcel-xlsx, pyexcel-ods, pyexcel-ods3 and pyexcel-xls.

**Comment by chfw** [comment]
iget_records vs get_records is memory efficient where the former does not hold all data from **reader** in memory before returning however both have no control over the underlying reader's behaviour.

**Comment by chfw** [comment]
https://github.com/pyexcel/pyexcel/commit/d2520fb370ef57f07e7332869d822f16c708bebf documents it.
