### ISSUE TITLE
just checking if there's any freeze pane features in pyexcel

### ISSUE THREAD

**Issue by simkimsia** [pyexcel/pyexcel#132]
Hi there, 

I did a quick search for the word 'freeze' in pyexcel.readthedocs, so found nothing. Is it safe to assume there's no freeze pane?

I am okay not having that feature. I'm just asking in case there's such a feature and its not documented

**Comment by chfw** [comment]
I am afraid that there is no such feature.

**Comment by chfw** [comment]
After pyexcel 0.6.0 will be released, let's revisit this again.

**Comment by simkimsia** [comment]
Sure no worries
