### ISSUE TITLE
Random Access To Individual Cell Could Be Clearer

### ISSUE THREAD

**Issue by flywire** [pyexcel/pyexcel#134]
1) [Random access to individual cell](https://pyexcel.readthedocs.io/en/latest/tutorial.html#random-access-to-individual-cell) would be clearer if example used different row and column numbers. Same with [Random access to individual cell](https://pyexcel.readthedocs.io/en/latest/tutorial.html#random-access-to-individual-cell).

2) Excel uses a base of A and 1 so it would be worth explicitly stated that the array base is 0,0.

**Comment by flywire** [comment]
Sorry, my suggestion to make it clearer is:

[Random access to individual cell](https://pyexcel.readthedocs.io/en/latest/tutorial.html#random-access-to-individual-cell) ...

```
>>> print(sheet[3, 2])
6
>>> print(sheet["D3"])
6
```

**Comment by chfw** [comment]
There are some examples:

![image](https://user-images.githubusercontent.com/4280312/38804709-38a0c818-416b-11e8-9c02-ce563dd43c25.png)

**Comment by flywire** [comment]
Yes, this is the example I referred to.

If column = 2 and row = 2 it is not clear to the reader which is row and which is column. If column = 3 and row = 2 the reader can easily see which is column and which is row..
