### ISSUE TITLE
Excel for Mac Date Offset

### ISSUE THREAD

**Issue by vborras** [pyexcel/pyexcel#135]
Hello, first of all, thanks for this great tool.

I'm facing an issue with date formatting: I have some cells containing '6-15', which was intended to represent an integer range, but Excel converts it to date, and when I read the file I get a datetime. This wouldn't be a problem if the datetime I got was correct, but instead of getting `2015-06-01` I'm getting `2011-05-11`.

For what I've seen, Excel stores dates as an integer with the difference in days from `1900-01-01`, but in older versions of Excel for Mac, the 'zero' date is `1904-01-01`, hence the wrong date.

The sheets I'm trying to import can't be modified, so I'm guessing if there's a way to force the reference date for reading, or to get the reference used in the book so I can correct the date after parsing it.

BTW, I think this is exactly the same problem as #54 . I've tested it in my computer, switching from one reference date to another, and the dates match.

**Comment by chfw** [comment]
For forcing the reference date, you can try [the advanced method](https://github.com/pyexcel/pyexcel#advanced-usage-fire), which can modify the data when each record is read out.

Let me re-visit #54 again and see if I can reproduce it.

**Comment by chfw** [comment]
You may find [these notes](http://docs.pyexcel.org/en/v0.6.0/two-liners.html) useful.

**Comment by vborras** [comment]
I'm sorry, I must be missing something, but I've done some tests and I can't see how I can apply the advanced method to reading a file.

**Comment by chfw** [comment]
`pip install pyexcel-xls==0.5.7` should fix the problem for you. Meanwhile, I am seeking to fix pyexcel-xlsx.

I am sorry to have been so slow to recognise it as a bug.

**Comment by vborras** [comment]
That's great news! I manually fixed the excel files I needed to import, but this will be really helpful in the future.

Thank you so much

**Comment by chfw** [comment]
https://openpyxl.readthedocs.io/en/stable/changes.html#id8 has fixed the on xlsx side so pyexcel-xlsx won't have such a problem.
