### ISSUE TITLE
How to Load Text File with Fixed Width Fields

### ISSUE THREAD

**Issue by flywire** [pyexcel/pyexcel#136]
All in the title. It would be good to explain in the docs.

**Comment by chfw** [comment]
as of now, pyexcel does not support it directly with fixed width fields because astropy had [excellent support](http://docs.astropy.org/en/stable/io/ascii/index.html) for text based tabular data.

**Comment by flywire** [comment]
You mean not support in the political sense.

There is probably more reason to demonstrate using fixed width than csv given lots of existing examples for csv and fixed width is still a common format, particularly with old software data files. It would be appropriate to add this simple example to the documentation (changing openpyxl to pyexcel) with a note to refer to astropy for more complex processing.

```
from itertools import tee, izip_longest
import openpyxl

def fixed_reader(df, data_start, data_end, indices, ws):
    with open(df, 'rb') as f:
        for line in range(0, data_start): next(f)
        for index, line in enumerate(f):
            if index == data_end: break
            start, end = tee(indices)
            next(end)
            line = line.rstrip('\r\n')
            # print([line[i:j].strip(' ') for i,j in izip_longest(start, end)]) # Uncomment for debug
            ws.append([line[i:j].strip(' ') for i,j in izip_longest(start, end)])
wb = openpyxl.Workbook()
ws = wb.active
fixed_reader('FixedWidth.dat', 3, 7, [0,1,6,8], ws)
wb.save('FixedWidth.xlsx')
```

**FixedWidth.dat**

```
1C4PJLAB1FW506827
SMT701PD57J348217
1GTEG15X541150523
3GYFNCE39CS56512
1GCGK24N9PE171689
K   U G7FU046394G
1FTEF25NXKNA45683
1G2PF37R8FP298952
JC2UA2127B059 944 5D
JH2PC4080AK380263
1FT7W2BT7FEC79068
```

**Comment by chfw** [comment]
wait for someone to write fix-width text as extension. hence, won't support it as a core solution.

please consider contribute it to pyexcel-text module if standalone one is not desirable.
