### ISSUE TITLE
File type not supported

### ISSUE THREAD

**Issue by mtn** [pyexcel/pyexcel#141]
Following the example from the `README`:

```python
>>> sheet = p.get_sheet(file_name="in.xlsm")
>>> sheet.save_as("test.html", display_length=10)
```

I end up with an error:

```
constants.FILE_TYPE_NOT_SUPPORTED_FMT % (file_type, action))
pyexcel.exceptions.FileTypeNotSupported: File type 'html' is not supported for write.
```

The only difference I'm aware of is the input file format, but the error message that is surfaced doesn't mention anything to do with this. Any ideas what might be wrong?

**Comment by chfw** [comment]
Ah you need to have 'test.sortable.html'

**Comment by mtn** [comment]
@chfw Thanks. Where can I find out more about that?

**Comment by chfw** [comment]
https://github.com/pyexcel/pyexcel/issues/139 and https://github.com/pyexcel-renderers/pyexcel-sortable#introduction, there but not specifically mentioned. 

I will take an action to state it clearly in pyexcel-sortables.

In principle, each plugin of pyexcel will have their own documentation so that pyexcel's documention will not grow horizontally.

**Comment by mtn** [comment]
Sorry, I didn't understand what you were saying initially. Were you suggesting that I should run this?

```python
>>> sheet = p.get_sheet(file_name="in.xlsm")
>>> sheet.save_as("test.sortable.html", display_length=10)
```

This produces the same error message.

**Comment by chfw** [comment]
Please run 'pip install pyexcel-sortable'

**Comment by mtn** [comment]
Awesome, thank you! It'd probably be helpful to add those notes (about the name requirement and requiring `sortable` in the `README`. 🎈

**Comment by mtn** [comment]
Thank you for making those updates!

**Comment by nilima89** [comment]
I am still getting file type not supported error after following the above steps. 
Code below:
import django_excel as excel
import pyexcel as p
import os

sheet1 = p.get_sheet(file_name='test.xlsx')
sheet1.save_as("test.sortable.html", display_length=10)

Error:

  File "C:\Users\nsahoo3\AppData\Local\Continuum\anaconda3\lib\site-packages\pyexcel\plugins\__init__.py", line 118, in find_file_type_from_file_name
    constants.FILE_TYPE_NOT_SUPPORTED_FMT % (file_type, action)

FileTypeNotSupported: File type 'html' is not supported for write.

**Comment by chfw** [comment]
'pip install pyexcel-sortable’?

**Comment by nilima89** [comment]
I did that too. do I have to import pyexcel-sortable along with pyexcel as well?

**Comment by chfw** [comment]
Nope, as long as in your current python environment, pyexcel-sortable is installed and is present. 

The way to verify is: `pip freeze` and check if you see both `pyexcel` and `pyexcel-sortable`.

If you are new to `pyexcel`, here's [more](https://lml.readthedocs.io/en/latest/design.html) to read. In a nutshell, `pyexcel` will automatically use plugin extension if it is installed and it is used. No need to explicitly do import.

**Comment by nilima89** [comment]
Thanks for the explanation. I do have both pyexcel and pyexcel-sortable installed. Is there any other reasons for getting the error.

pycparser==2.19
pyexcel==0.5.13
pyexcel-io==0.5.17
pyexcel-odsr==0.5.2
pyexcel-sortable==0.0.2

**Comment by chfw** [comment]
What else? I am scratching my heads now. It is unlikely that your python and pip command are not in the same environment?

try:

$ which python
$ which pip 

and see if they come from the same python path. It may get a bit funny inside anaconda.

And you can do these:

1) pip uninstall pyexcel pyexcel-sortable
2) repeat step 1 until pip says there is no more packages
3) create a virtualenv yourself, then pip install pyexcel and pyexcel-sortable only inside your newly created virtual environment
4) try your sample script, and it shall work!
