### ISSUE TITLE
Insert new row at row index

### ISSUE THREAD

**Issue by coler-j** [pyexcel/pyexcel#143]
Is there a function/shortcut to add a new row (to add a second header), or is there at least an `insert` method for the row object?

Something like:

    new_row = ['a', 'b', 'c']
    sheet.row.insert(index=1, row=new_row)

**Comment by chfw** [comment]
It does not have an intuitive method as you described but row should have such a method.

for now, you use [paste method](http://docs.pyexcel.org/en/latest/generated/pyexcel.Sheet.paste.html#pyexcel.Sheet.paste):

`def paste(self, topleft_corner, rows=None, columns=None)`

for example:

`sheet.paste((1,0), rows=[new_row])`

**Comment by coler-j** [comment]
Alright, I ended up just modifying my initial dictionary used to create the Sheet instead and inserted the additional row of data there.
