### ISSUE TITLE
Whoosh / elasticsearch integration

### ISSUE THREAD

**Issue by patarapolw** [pyexcel/pyexcel#145]
I manage to put pyexcel into Whoosh, but I have to

    writer = None

    for record in pyexcel.iget_records(file_name=RAW_DATA_PATH, sheet_name=data_type):
        if writer is None:
            schema = whoosh.fields.Schema(**dict.fromkeys(record.keys(), whoosh.fields.TEXT(stored=True)))
            searchers[data_type] = whoosh.index.create_in("whoosh_index", schema)
            writer = searchers[data_type].writer()

        record = dict([(k, str(v)) for k, v in record.items()]))

It is odd that I have to convert every single cells into string. Otherwise, how would let Whoosh know it is an int?

https://github.com/patarapolw/HanziLevelUp/blob/master/HanziLevelUp/quiz.py#L19

**Comment by chfw** [comment]
turn it off: http://docs.pyexcel.org/en/latest/api.html#auto-detect-int 

`iget_records(file_name=RAW_DATA_PATH, sheet_name=data_type, auto_detect_int=False)`
