### ISSUE TITLE
auto_detect_float=True causes all string variations of "nan" to be treated as a NaN entity instead of a string

### ISSUE THREAD

**Issue by PLPeeters** [pyexcel/pyexcel#146]
When `auto_detect_float` is set to `True`, any cell with a string value of `nan`, `NaN`, `naN`, etc. will be converted to the `NaN` entity instead of being treated as a string. Possible fixes:

* Only do this if the field actually contains the string `NaN`, with this exact case
* Add an option to treat all variations of `nan` as a string instead of converting it to the `NaN` entity
* Perhaps both of the above

**Comment by chfw** [comment]
OK. Will look at it

**Comment by chfw** [comment]
please try with: pyexcel-io==0.5.8

it takes effects on csv, tsv formats so far.

**Comment by PLPeeters** [comment]
Great! I don't have the time to test it right now, but I checked the code and it looks like it does exactly what I outlined above, so all good. Thanks for the fix!
