### ISSUE TITLE
Load Excel files from Cloud Storage (Google, S3, etc.)

### ISSUE THREAD

**Issue by coler-j** [pyexcel/pyexcel#147]
This library seems to expect excel files to only exist on the local filesystem for read and write purposes. 

What is the recommended way to load a file (say on the AWS S3 file storage backend) and use this library?

**Comment by coler-j** [comment]
Never-mind, using Django, once I had the file saved to my model, I was able to just do the following to convert the file to a sheet:

    file = my_model.saved_file.file
    sheet = pyexcel.get_sheet(file_stream=file, file_type='xlsx')

I guess as much documentation that exists for this project, it is just lacking in functional clarity.

**Comment by chfw** [comment]
yep, it is challenging to write the documentation that people likes. I will try to improve.
