### ISSUE TITLE
Reading and writing multiple sheet from ods file 

### ISSUE THREAD

**Issue by erotavlas-turbo** [pyexcel/pyexcel#150]
Hi,
I'm using the code reported [here](http://docs.pyexcel.org/en/latest/tutorial.html#read-multiple-sheet-excel-file) in order to read and write multiple sheet form an ods file.
If the ods file does not contains any [external reference](https://help.libreoffice.org/Calc/Referencing_a_Cell_in_Another_Document) to other files, the name of the sheet is read correctly. While in presence of an external reference, the name of the file become the name of the external link.
Is this an expected behaviour?

```
# get sheet as dictionary
for name in book.to_dict().keys():
    print(name) # remove 'file:///path/file.ods'#$'sheet'
```
For the moment, I solved by parsing the name.
Thank you

**Comment by chfw** [comment]
To be honest, this is a new thing for me. What's your expectation in this case?

Could you please share an example ods file with me? so that I can have a look.

**Comment by erotavlas85** [comment]
You can consider the following example:
```
book=pyexcel.get_book(file_name=fileName)
  # get sheets as dictionary
  for name in book.to_dict().keys():
    # Note: necessary for ods file 'file:///absolute_path/file.ods'#$'sheet'
    name=name.split("#")
    if len(name) == 1:
      name=name[0]
    else:
      name=name[1]
```

I tried with `.xls` format and it works well without the hack. So the problem only involves `.ods` format. Do you think that it is something related to pyexcel?!

**Comment by chfw** [comment]
nope, pyexcel itself does "logistics" only. it uses other 3rd party library to fulfil the file reading and writing task. Here's the [architecture](http://docs.pyexcel.org/en/latest/architecture.html). 

I will have a look at it.

**Comment by chfw** [comment]
`pip install pyexcel pyexcel-ods`

```
>>> import pyexcel as p
>>> e=p.get_book(file_name="example.ods")
>>> e.sheet_names()
['Dog', 'Cat', 'Mouse', "'file:///home/tore/Desktop/data.ods'#Dog", "'file:///home/tore/Desktop/data.ods'#Mouse"]
>>> e["'file:///home/tore/Desktop/data.ods'#Dog"]
'file:///home/tore/Desktop/data.ods'#Dog:
+----+
| 1  |
+----+
| 3  |
+----+
| 6  |
+----+
| 2  |
+----+
| 4  |
+----+
| 7  |
+----+
| 3  |
+----+
| 5  |
+----+
| 8  |
+----+
| 4  |
+----+
| 6  |
+----+
| 9  |
+----+
| 5  |
+----+
| 7  |
+----+
| 10 |
+----+
| 6  |
+----+
| 8  |
+----+
| 11 |
+----+
| 7  |
+----+
| 9  |
+----+
>>> e["'file:///home/tore/Desktop/data.ods'#Mouse"]
'file:///home/tore/Desktop/data.ods'#Mouse:
+----+
| 1  |
+----+
| 2  |
+----+
| 3  |
+----+
| 4  |
+----+
| 5  |
+----+
| 6  |
+----+
| 7  |
+----+
| 8  |
+----+
| 9  |
+----+
| 10 |
+----+
| 11 |
+----+
| 12 |
+----+
| 13 |
+----+
| 14 |
+----+
```

**Comment by chfw** [comment]
```
>>> e.to_dict()
OrderedDict([('Dog', [[3], [6], [2], [4], [7], [3], [5], [8], [4], [6], [9], [5]]), ('Cat', [[]]), ('Mouse', [[1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], [13], [14], [0], [0], [0], [0], [0]]), ("'file:///home/tore/Desktop/data.ods'#Dog", [[1], [3], [6], [2], [4], [7], [3], [5], [8], [4], [6], [9], [5], [7], [10], [6], [8], [11], [7], [9]]), ("'file:///home/tore/Desktop/data.ods'#Mouse", [[1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], [13], [14]])])
>>> e.to_dict().keys()
odict_keys(['Dog', 'Cat', 'Mouse', "'file:///home/tore/Desktop/data.ods'#Dog", "'file:///home/tore/Desktop/data.ods'#Mouse"])
```

**Comment by erotavlas85** [comment]
Exactly, by reading an `.ods` file there are duplicate reference to the sheet name and to the linked sheet name. This does not happen with `.xls` file.
Is this is an expected behaviour of `.ods` format or is it something related to pyexcel or its architecture?

```
import pyexcel
def readData(fileName):
    book=pyexcel.get_book(file_name=fileName)
    # get sheets as dictionary
    for name in book.to_dict().keys():
        # Note: necessary for ods file 'file:///absolute_path/file.ods'#$'sheet'
        print(name)
readData("example.ods")
readData("example.xls")
```

**Comment by chfw** [comment]
Be assured that pyexcel does not auto-generate or auto-remove data for you. But it does ignore styles, fonts, images other than data itself.

Let me check the ods specification.

**Comment by chfw** [comment]
Sorry, I failed to check till today. Hence, I am not sure I will ever do this. So I am going to close this.
