### ISSUE TITLE
Error codes in error cells instead of None

### ISSUE THREAD

**Issue by vkosh** [pyexcel/pyexcel#151]
iget_array, get_array, get_records, iget_records returns error code values (e.g. "42", "15", etc.) instead of None or something in error cells.
I think, there's a [good place](https://github.com/pyexcel/pyexcel-xls/blob/master/pyexcel_xls/xlsr.py#L90) to handle cell_type == xlrd.XL_CELL_ERROR.

Test file: [test.xlsx](https://github.com/pyexcel/pyexcel/files/2274743/test.xlsx)

**Comment by chfw** [comment]
```
>>> import pyexcel as p
>>> s=p.get_sheet(file_name='tests/fixtures/pyexcel_issue_151.xlsx', library="pyexcel-xls")
Traceback (most recent call last):
...
    raise NotImplementedError("formatting_info=True not yet implemented")
NotImplementedError: formatting_info=True not yet implemented
>>> s=p.get_sheet(file_name='tests/fixtures/pyexcel_issue_151.xlsx', library="pyexcel-xlsx")
>>> s
Лист1:
+------+----------+
| #N/A | zzzz1234 |
+------+----------+
```

**Comment by vkosh** [comment]
```python
>>> import pyexcel as p
>>> p.get_array(file_name='test.xlsx')
[[42, 'zzzz1234']]
>>> p.get_array(file_name='test.xlsx', library="pyexcel-xls")
[[42, 'zzzz1234']]
>>> p.get_array(file_name='test.xlsx', library="pyexcel-xlsx")
[['#N/A', 'zzzz1234']]
```

All tests gives no clue how to distinguish user data from an error.

**Comment by vkosh** [comment]
It's ok for single untyped output of excel file as is. But in case of importing to something with strict typing (e.g. database) it will be a problem. I didn't find a way to handle such error cells in client code. I think, that "the right" solutions are too complex and will break BC (e.g. to return Cell/ErrorCell objects in get_* methods). So I propose to return None in error cells - as there's no useful data in such cells. Another possible solution is to pass error_cell_callback to get_* methods and let user handle error data by himself.

**Comment by chfw** [comment]
before we try to expose error_cell_callback(which will work only with pyexcel-xls, unless I try to dig out pyexcel-xlsx and provide the same option), can you consider the following code?

```
>>> import pyexcel as p
>>> s=p.get_sheet(file_name='tests/fixtures/pyexcel_issue_151.xlsx', library='pyexcel-xls', skip_hidden_row_and_column=False)
>>> s
Лист1:
+------+----------+
| #N/A | zzzz1234 |
+------+----------+
>>> def my_renderer(row):
...     if(row[0]=='#N/A'):
...         row[0] = None
...     return row
... 
>>> s=p.get_sheet(file_name='tests/fixtures/pyexcel_issue_151.xlsx', library='pyexcel-xls', skip_hidden_row_and_column=False, row_renderer=my_renderer)
>>> s
Лист1:
+---+----------+
|   | zzzz1234 |
+---+----------+
```

**Comment by chfw** [comment]
please try `pip install pyexcel-xls==0.5.8`
