### ISSUE TITLE
lml requirement loosened in pyexcel 0.5.9, but not in pyexcel-io

### ISSUE THREAD

**Issue by cloneluke** [pyexcel/pyexcel#155]
In pyexcel 0.5.9, the dependency on lml went from =0.0.1 to >=0.0.1, but pyexcel-io, did not loosen this requirement, so when 0.5.9 pyexcel is installed, a dependency issue occurs:

`pkg_resources.ContextualVersionConflict: (lml 0.0.4 (/usr/local/lib/python3.5/dist-packages), Requirement.parse('lml==0.0.1'), {'pyexcel-io'})`

https://github.com/pyexcel/pyexcel/blob/78a8dc737a0b65499f9e10ffe2696425a2c439db/requirements.txt

https://github.com/pyexcel/pyexcel/blob/78a8dc737a0b65499f9e10ffe2696425a2c439db/setup.py#L51

https://github.com/pyexcel/pyexcel/commit/f86dbf9cd11e5db4360a91e995b2013d751e9858#diff-b4ef698db8ca845e5845c4618278f29a

by @chfw 

https://github.com/pyexcel/pyexcel-io/blob/d2e1e8ad9911d352211c50570949b81227120a9f/requirements.txt#L2

https://github.com/pyexcel/pyexcel-io/blob/317e170118bed0b3db7d4ce97c05e65e7d70f773/setup.py#L50

This may be an issue for the pyexcel-io, but since this repo was the breaking change, I opened it here
The newest version of lml is 0.0.4

https://pypi.org/project/lml/#history

**Comment by chfw** [comment]
hmm! I see the point. Probably I should have sticked with lml==0.0.1 for 0.5.9

And then get every pyexcel member to jump together to lml==0.0.4.

**Comment by chfw** [comment]
I have replaced pyexcel 0.5.9 with 0.5.9.1. Thanks for reporting it.
