### ISSUE TITLE
Open protected excel files

### ISSUE THREAD

**Issue by jmainar** [pyexcel/pyexcel#158]
Can I open an excel file (xls extension),  password protected (I know the password),  using pyexcel module?
If someone can help me....

Thanks in advance

**Comment by chfw** [comment]
I don't think pyexcel can open protected excel file at all. Maybe you should consider other libraries or even try things outside python.

**Comment by jmainar** [comment]
I resolved this issue using the python module win32com.client.
Thanks anyway for your help.
