### ISSUE TITLE
I can parse some XLSX files but not others. Why is that?

### ISSUE THREAD

**Issue by deepsnow** [pyexcel/pyexcel#162]
Hello!

Myself and two colleagues are trying to parse XLSX files in Python code after retrieving the XLSX file from an e-mail inbox as a message attachment.

Here's a snippet of that code:

![image](https://user-images.githubusercontent.com/334971/49833171-b5991480-fd66-11e8-9201-412489f6c594.png)

The line

`schedule = pyexcel.get_array(file_stream=StringIO(content), file_type='xlsx')`

works for two of the XLSX files in the targeted inbox. But, for all of the XLSX file attachments in the box, that line throws the following exception:

![image](https://user-images.githubusercontent.com/334971/49833353-3c4df180-fd67-11e8-8bff-cf35eb80691a.png)

I don't know how to find a significant difference between the XLSX files in question that can be parsed, and those that can be parsed.

The best clue that I have thus far is that if one of my colleagues modifies one the parse-able XLSX files in his desktop version of Excel 2016, and then submits that modified file to the inbox, then we find that the modified file becomes an attachment that causes the script to fail with a BadZipFile exception.

![image](https://user-images.githubusercontent.com/334971/49833834-b6cb4100-fd68-11e8-923f-83903157f21b.png)

I'll attach several of the sample files.

The ones that can be parsed (by the script in its current form) are:

- ScheduleData 2018-11-04 to 2018-11-10.xlsx
- ScheduleData 2018-11-11 to 2018-11-17.xlsx

The ones that cannot be parsed are:

- ScheduleData 2018-12-02 to 2018-12-08.xlsx
- ScheduleData 2018-12-16 to 2018-12-22.xlsx
- ScheduleData 2018-12-23 to 2018-12-29.xlsx
- SOC Schedule.xlsx

I welcome any input on how I can get the script to parse both the former and the latter set of XLSX files.

Thank you,

[ScheduleData 2018-11-04 to 2018-11-10.xlsx](https://github.com/pyexcel/pyexcel/files/2669667/ScheduleData.2018-11-04.to.2018-11-10.xlsx)
[ScheduleData 2018-11-11 to 2018-11-17.xlsx](https://github.com/pyexcel/pyexcel/files/2669669/ScheduleData.2018-11-11.to.2018-11-17.xlsx)
[ScheduleData 2018-12-02 to 2018-12-08.xlsx](https://github.com/pyexcel/pyexcel/files/2669670/ScheduleData.2018-12-02.to.2018-12-08.xlsx)
[ScheduleData 2018-12-16 to 2018-12-22.xlsx](https://github.com/pyexcel/pyexcel/files/2669671/ScheduleData.2018-12-16.to.2018-12-22.xlsx)
[ScheduleData 2018-12-23 to 2018-12-29.xlsx](https://github.com/pyexcel/pyexcel/files/2669672/ScheduleData.2018-12-23.to.2018-12-29.xlsx)
[SOC Schedule.xlsx](https://github.com/pyexcel/pyexcel/files/2669673/SOC.Schedule.xlsx)

**Comment by chfw** [comment]
It turns out that it is not as bad as I thought. Your files are genuine and can be read without problems. Next question, why the file stream is corrupted in the program so that python's zipfile cannot recognise it?

```
Python 2.7.10 (default, Aug 17 2018, 17:41:52) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyexcel as p
>>> p.get_array(file_name="ScheduleData.2018-12-23.to.2018-12-29.xlsx")
[[u'', u'Position', u'Total: Paid Hours', u'Sun, Dec 23', u'Mon, Dec 24', u'Tue, Dec 25'...
>>> p.get_array(file_name="ScheduleData.2018-12-02.to.2018-12-08.xlsx")
[[u'', u'Position', u'Total: Paid Hours', u'Sun, Dec 2', u'Mon, Dec 3', u'Tue, Dec 4',...
>>> p.get_array(file_name="ScheduleData.2018-12-16.to.2018-12-22.xlsx")
[[u'', u'Position', u'Total: Paid Hours', u'Sun, Dec 16', u'Mon, Dec 17', u'Tue, Dec 18', ...
```

The attached file is perfect and those erroneous files can be read out from my side. And I have used both pyexcel-xls and pyexcel-xlsx to read and both did not report bad zip problem. Here are my verions:

```
xlrd==1.1.0
pyexcel-xls==0.5.8
pyexcel==0.5.10
```

For your information both pyexcel-xls and pyexcel-xlsx can read xlsx but pyexcel-xls cannot write xlsx file. pyexcel-xlsxw can complement pyexcel-xls with xlsx writing capability.

**Comment by deepsnow** [comment]
@chfw 

Thank you for your informative reply!

Your observations helped me to realize that the e-mail messages in question may have more than one attachment, and that proved to be true. In addition, it appears that the Python lib we're using to fetch the messages from the inbox doesn't guarantee the order in which attachments will be presented when the list of attachments (belonging to each fetched e-mail message) is processed...

When we added new logic to test each attachment and positively identify the XLSX file, and then ensure that this attachment is the one that is fed into pyexcel.get_array(...).

Thanks again!
