### ISSUE TITLE
lml>=0.0.4 - Produces import errors. 

### ISSUE THREAD

**Issue by smentek** [pyexcel/pyexcel#163]
Current **lml 0.0.9** (lml>=0.0.4) does not seem to work with your code. 
I hardcoded it to lml==0.0.6 in my project in order to resolve it.  

I use:
pyexcel==0.5.8
pyexcel-xlsx==0.5.6

**Comment by chfw** [comment]
Thanks for your report. Let me check.

**Comment by chfw** [comment]
https://travis-ci.org/pyexcel/pyexcel/jobs/463194613#L639

The tests went OK. Could you be a bit more specific?

**Comment by smentek** [comment]
Hmm... Sorry It have to be sth related to imports in my app. Imports works only on explicit lml==0.0.9 (or any other version) I noticed lots of releases on https://pypi.org/project/lml/ so I jumped to the conclusion since the error is about that lib.

Application code:
from pyexcel_xlsx import get_data, save_data
f = io.BytesIO(file_content)
data_file = get_data(f)

Error:
...
    from pyexcel_xlsx import get_data, save_data
  File "/usr/local/lib/python3.6/site-packages/pyexcel_xlsx/__init__.py", line 10, in <module>
    from pyexcel_io.plugins import IOPluginInfoChain
  File "/usr/local/lib/python3.6/site-packages/pyexcel_io/__init__.py", line 15, in <module>
    from .io import get_data, iget_data, save_data  # noqa
  File "/usr/local/lib/python3.6/site-packages/pyexcel_io/io.py", line 14, in <module>
    from pyexcel_io.plugins import READERS, WRITERS
  File "/usr/local/lib/python3.6/site-packages/pyexcel_io/plugins.py", line 10, in <module>
    from lml.loader import scan_plugins_regex
ImportError: cannot import name 'scan_plugins_regex'

**Comment by chfw** [comment]
Your stacktrace looks like incomparability between pyexcel-io and lml. So pyexcel-io wants newer version of lml but old version is installed.
