### ISSUE TITLE
Dates export to ods are 'styled' as numbers

### ISSUE THREAD

**Issue by fpuga** [pyexcel/pyexcel#164]
I'm not sure, if this issue belongs to this repo, or even if it is in the scope of this library, but at least, write it can save some time to others.

When a "date type" is saved to xlsx or ods it is correctly retrieved again by code. But when opening the files with libreoffice, the xlsx file have styled (correctly the date as a date), but the ods file have styled it (incorrectly) as a number.

A code sample to reproduce the issue:

```python
import pyexcel
import datetime

data = [[1, datetime.date(2019, 12, 30)], [2, datetime.date(2019, 11, 30)]]
pyexcel.save_as(array=data, dest_file_name="/tmp/example.xlsx")
pyexcel.save_as(array=data, dest_file_name="/tmp/example.ods")
data_xlsx = pyexcel.get_array(file_name="/tmp/example.xlsx")
# [[1, datetime.date(2019, 12, 30)], [2, datetime.date(2019, 11, 30)]]

data_ods = pyexcel.get_array(file_name="/tmp/example.ods")
# [[1, datetime.date(2019, 12, 30)], [2, datetime.date(2019, 11, 30)]]
```
![captura de pantalla de 2019-01-25 20-55-44](https://user-images.githubusercontent.com/932124/51769355-26ac4580-20e3-11e9-9f3e-3dd4784a5313.png)
![captura de pantalla de 2019-01-25 20-56-03](https://user-images.githubusercontent.com/932124/51769367-29a73600-20e3-11e9-9838-2e828975abe0.png)

```
$ pip list | grep pyexcel
pyexcel              0.5.10     
pyexcel-io           0.5.11     
pyexcel-ods          0.5.4      
pyexcel-xls          0.5.8      
pyexcel-xlsx         0.5.6
```

I also make a test with `pyexcel-ods3` and the result is better.

![captura de pantalla de 2019-01-25 20-59-52](https://user-images.githubusercontent.com/932124/51769540-a6d2ab00-20e3-11e9-9343-8193830cb151.png)

**Comment by chfw** [comment]
Will have look. It is related to how datetime written using ezodf.

Have you tried with pyexcel-ods? Same behavior?

**Comment by fpuga** [comment]
The image tagged in my question as `example.ods` is using `pyexcel-ods==0.5.4`. The image tagged as `example.ods with pyexcel-ods3` is with `pyexcel-ods3==0.5.3` and `pyexcel-ezodf==0.3.4`

So, with pyexcel-ods is "rendereded" as a number with pyexcel-ods3 is "rendered" as date + time.

Thanks for take a look a it.

**Comment by chfw** [comment]
transferred to pyexcel-ods repo as it is plugin specific problem. others are not affected.
