### ISSUE TITLE
Empty (but formatted) rows are read for .ods files

### ISSUE THREAD

**Issue by fpuga** [pyexcel/pyexcel#165]
Given a file like this one

![captura de pantalla de 2019-01-26 18-15-20](https://user-images.githubusercontent.com/932124/51790456-dfcb5800-2195-11e9-937b-a2776a8b8a99.png)

If it is saved as .xlsx everything works fine:

```
import pyexcel
data_xlsx = pyexcel.get_array(file_name="excel_formato_mas_alla_de_los_datos.xlsx")
# [[1, 'a', datetime.date(2019, 12, 30)], [2, 'b', datetime.date(2019, 11, 30)]]
```

But when saving the file as .ods, rows 3 and 4 that are empty of content but have a border, are retrieved with null values:

```
data_ods = pyexcel.get_array(file_name="excel_formato_mas_alla_de_los_datos.ods")
# [[1, 'a', datetime.date(2019, 12, 30)], [2, 'b', datetime.date(2019, 11, 30)], ['', '', ''], ['', '', '']]
```
It's curious that only happens with the rows. The columns D, E also are empty but with border and are not added to the pyexcel array.

[excel_formato_mas_alla_de_los_datos.xlsx](https://github.com/pyexcel/pyexcel/files/2799263/excel_formato_mas_alla_de_los_datos.xlsx)

It is happening to me with `pyexcel-ods` and `pyexcel-ods3`

```
pyexcel             0.5.10     
pyexcel-io         0.5.11     
pyexcel-ods      0.5.4      
pyexcel-xls       0.5.8      
pyexcel-xlsx      0.5.6

pyexcel-ezodf    0.3.4
pyexcel-ods3     0.5.3
```

**Comment by chfw** [comment]
have you tried `skip_empty_rows`? https://github.com/pyexcel/pyexcel-io/blob/master/pyexcel_io/sheet.py#L39

**Comment by fpuga** [comment]
That works. I didn't know about that option. Sorry for the troubles.

I'm closing this myself
