### ISSUE TITLE
merge updated get_dict back into excel sheet

### ISSUE THREAD

**Issue by zelmor** [pyexcel/pyexcel#167]
Hi. I have a source csv file, and an excel table for which the desired input field starts at A11. I have created 2 dicts with 
`dataSource = pyexcel.get_dict(file_name="herebefile.csv", delimiter=';', )`
`dataEntry = pyexcel.get_dict(file_name="tempOutput.xlsx", name_columns_by_row=9)`

This produced a dict which I updated with values from dataSource as such:
`dataEntry.update({'Client': client, 'Order': orderNo, 'Project Code': (dataSouce.get(('projectNumber'))), 'Date': (dataSource.get(('date'))), 'Workhours': (dataSource.get(('hours')))})`

This, I believe has produced the desired result of updating the values in the target dict, however, I do not know of a way to save or merge the dictionary back into the excel sheet. Could you give me some pointers, please?

**Comment by chfw** [comment]
have you checked out this tutorial? http://docs.pyexcel.org/en/latest/quickstart.html#export-a-dictionary-of-single-key-value-pair
