### ISSUE TITLE
Optional test dependency on pyexcel-handsontable

### ISSUE THREAD

**Issue by jayvdb** [pyexcel/pyexcel#169]
The tests state they depend on `pyexcel-handsontable`, but that depends on @pyecharts , has problem https://github.com/pyexcel-renderers/pyexcel-handsontable/issues/5 , but generally is less mature than `pyexcel`.

The test suite should at least skip the relevant tests when `pyexcel-handsontable` is not installed, so that the packagers dont need to get @pyecharts working before they can get @pyexcel packaged with tests passing.

**Comment by chfw** [comment]
Let me have a look. I may have winded myself up.
