### ISSUE TITLE
get_sheet {IndexError}list index out of range // XLSX can't be opened

### ISSUE THREAD

**Issue by lbesnard** [pyexcel/pyexcel#176]
Hi 

I've found some issues trying to open some xlsx files:

```python
pyexcel.get_sheet(file_name="BAD.xlsx")   
```
returns ```{IndexError}list index out of range```

I then opened the BAD.xlsx with libreoffice and exported it as a xlsx 2009/2013 to GOOD.xlsx. 
then running the same command was successful
```pyexcel.get_sheet(file_name="GOOD.xlsx")```

Files attached
[GOOD.xlsx](https://github.com/pyexcel/pyexcel/files/2954804/GOOD.xlsx)
[BAD.xlsx](https://github.com/pyexcel/pyexcel/files/2954805/BAD.xlsx)

I'm running the latest versions of the pyexcel packages

Cheers!

**Comment by chfw** [comment]
Reproduced

**Comment by chfw** [comment]
In next release, pyexcel.exceptions.NoDataRead exception will be raised, to indicate no data read. I thought passing empty data structure around is not effective as passing an exception.

**Comment by chfw** [comment]
I had a change in mind as people are not used to get an exception when '{}' is returned so giving:

{"<No data>": [[]]]} to a sheet
and
{} to a book.

**Comment by lbesnard** [comment]
@chfw thanks a lot for the help. I have installed the new release. However do you know what is wrong with this file ? I still cannot seem to parse it. 
Cheers

**Comment by chfw** [comment]
I have a library which can handle it: pyexcel-xlsxr, which uses lxml to read it instead.

I tried it and it works.

in order to use it, you need to pass: get_sheet(.... library='pyexcel-xlsxr') after `pip install pyexcel-xslxr`.

or, you have into pip uninstall pyexcel-xlsx pyexcel-xls so that no xlsx reader will compete for pyexcel-xlsxr.

**Comment by chfw** [comment]
Oh...no.. there is loads of data inside.

**Comment by chfw** [comment]
`OrderedDict([('ag data', [['GLOBAL ATTRIBUTES', '', 'Comments', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['title', 'Coffs Harbour', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['project', 'Integrated Marine Observing System (IMOS)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['original_project_name', 'Phytoplankton and oceanography of the Coffs Harbour region, Eastern Australia', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['institution', 'Macquarie University', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['abstract', 'This data was collected as part of a time-series survey investigating the phytoplankton and oceanography of the Coffs Harbour region, Eastern Australia (Armbrecht, L., 2014, PhD Thesis, Macquarie University, Australia). Water samples for pigment analysis (HPLC) were collected monthly along two cross shelf transects (CH-Line, B-Line) and one intermediate coastal station (SS) off Coffs Harbour (~30°S, 153°E), Eastern Australia, between May 2011 and September 2012. The exact sampling locations (coordinates) and times were recorded. Two of the sampling stations (CH3 and CH5) are also the sites of permanent IMOS moorings (CH070 and CH100, respectively). Phytoplankton and zooplankton samples were collected at the same locations (data available at https://catalogue.aodn.org.au/geonetwork/srv/eng/metadata.show?uuid=f7502841-a2c7-4437-b557-20ef89e754e0). The data can be used for Ocean Colour sensor validation. ', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['conventions', 'IMOS biological data format (v1.0)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['date_created', '', '', '', ''...`
