### ISSUE TITLE
Problem with installing pyexcel through proxy

### ISSUE THREAD

**Issue by axpek** [pyexcel/pyexcel#179]
Hello! 
I'm trying to install pyexcell package with following command:
pip install pyexcel --proxy=login:pswd@proxy.address:1111" 
and getting the following error:
Collecting pyexcel
    Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None))
 after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection
.VerifiedHTTPSConnection object at 0x0000000004887588>, 'Connection to pypi.org
timed out. (connect timeout=15)')': /simple/pyexcel/
  Could not find a version that satisfies the requirement pyexcel (from versions: )
No matching distribution found for pyexcel

Please help me with this issue.

**Comment by axpek** [comment]
The following decision doesn't work too:
pip install package C:\IT\pyexcel-0.5.13.tar.gz
Processing c:\it\pyexcel-0.5.13.tar.gz
Collecting package
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None))
 after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection
.VerifiedHTTPSConnection object at 0x0000000004882A20>, 'Connection to pypi.org
timed out. (connect timeout=15)')': /simple/package/

**Comment by chfw** [comment]
try

pip install requests

if you have the same problem, then your proxy does not work

**Comment by axpek** [comment]
pip install requests
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-pac
kages (2.21.0)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\programdata\anaconda3
\lib\site-packages (from requests) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\li
b\site-packages (from requests) (2018.11.29)
Requirement already satisfied: idna<2.9,>=2.5 in c:\programdata\anaconda3\lib\si
te-packages (from requests) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\programdata\anaconda3
\lib\site-packages (from requests) (3.0.4)

My browser works through out proxy so I think it works. Is there any way to install it manually?

**Comment by chfw** [comment]
You have conda so please try conda install pyexcel

**Comment by chfw** [comment]
https://anaconda.org/conda-forge/pyexcel

**Comment by axpek** [comment]
conda install -c conda-forge pyexcel
Solving environment: failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/c
onda-forge/win-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

ProxyError(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=44
3): Max retries exceeded with url: /conda-forge/win-64/repodata.json (Caused by
ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 au
thenticationrequired')))"))

Can you tell me where I can download pyexcel files directly and copy this files to anaconda 3 working folder? OS Windows 7 
The problem with proxy is on my job but I can download pyexcel files from my home computer. 
I've already copied pyexcel  files from my home working anaconda directory to C:\ProgramData\Anaconda3\Lib\site-packages but when I'm trying to import pyexcel in jupyter notebook I'm getting the following error:
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-8cf5dfa38a48> in <module>
      6 import xlwt
      7 import win32com.client as win32
----> 8 import pyexcel as p

C:\ProgramData\Anaconda3\lib\site-packages\pyexcel\__init__.py in <module>
     10     :license: New BSD License, see LICENSE for more details
     11 """
---> 12 from .book import Book
     13 from .core import (
     14     save_as,

C:\ProgramData\Anaconda3\lib\site-packages\pyexcel\book.py in <module>
      9 """
     10 import pyexcel._compact as compact
---> 11 from pyexcel.sheet import Sheet
     12 from pyexcel.internal.meta import BookMeta
     13 from pyexcel.internal.common import SheetIterator

C:\ProgramData\Anaconda3\lib\site-packages\pyexcel\sheet.py in <module>
     12 import pyexcel._compact as compact
     13 import pyexcel.constants as constants
---> 14 from pyexcel.internal.sheets.row import Row as NamedRow
     15 from pyexcel.internal.sheets.column import Column as NamedColumn
     16 from pyexcel.internal.sheets.matrix import Matrix

C:\ProgramData\Anaconda3\lib\site-packages\pyexcel\internal\__init__.py in <module>
      8     :license: New BSD License
      9 """
---> 10 from pyexcel.internal.plugins import PARSER, RENDERER  # noqa
     11 from pyexcel.internal.generators import BookStream, SheetStream  # noqa
     12 from pyexcel.internal.source_plugin import SOURCE  # noqa

C:\ProgramData\Anaconda3\lib\site-packages\pyexcel\internal\plugins.py in <module>
      8     :license: New BSD License
      9 """
---> 10 from lml.plugin import PluginManager
     11 
     12 

ModuleNotFoundError: No module named 'lml'

**Comment by axpek** [comment]
Please help me resolve this issue. Your help will much appreciated with contribution

**Comment by chfw** [comment]
stale support question
