### ISSUE TITLE
Do not interpret numbers as float?

### ISSUE THREAD

**Issue by mvdw** [pyexcel/pyexcel#18]
I tried the following code to convert a ods with python 2.7:

```python
import pyexcel as pe
import pyexcel.ext.ods3
pyexcel.save_as(file_name=args.source, dest_file_name=args.destination)
```

The result has the following problem:

If a cell contains "1", then it is converted into "1.0".  There is a nice example about formatters at https://pyexcel.readthedocs.org/en/latest/tutorial03.html#convert-a-column-of-numbers-to-strings, but it does not explain how to prevent the cell to become float. Maybe this is simply a documentation issue?

Remark: Yes, my spreadsheet contains cells with a number 1, which should in fact be strings - but entering a string "1" in a spreadsheet is way slower than just entering a number...

**Comment by chfw** [comment]
ODS format does not have integer value unless you format them as string either in ods file itself or format them as int using pyexcel.sheet.format 

http://books.evc-cit.info/odbook/ch05.html#table-number-cells-section

**Comment by mvdw** [comment]
1. The numbers are stored in the ods file as numbers, not strings, since it would require a lot of manual work to type them in as strings. We code to save work...
2. I tried to use a format, but concluded the same as in the example at https://pyexcel.readthedocs.org/en/latest/tutorial03.html#convert-a-column-of-numbers-to-strings : the ".0" is still added. So, this does nothing for me.
3. Still, if I export as follows with libreoffice it works fine:
```
libreoffice --headless -env:UserInstallation=file:///tmp/Lib1_Conversion --convert-to csv:"Text - txt - csv (StarCalc)":44,34,76 --outdir ./source/generated ./source/model/properties.ods
```
Hence, pyexcel offers no alternative for libreoffice? I should look for another tool?

**Comment by chfw** [comment]
>>> sheet.column.format(0, int) # <-- add this one
>>> sheet.column.format(0, str)
>>> sheet.column["userid"]
['10120.0', '10121.0', '10122.0']
