### ISSUE TITLE
curious problem with datetime

### ISSUE THREAD

**Issue by artgoldberg** [pyexcel/pyexcel#180]
Using pyexcel to read some csv data. It throws this error:

    cell_text = 'References'

        def detect_date_value(cell_text):
            """
            Read the date formats that were written by csv.writer
            """
            ret = None
            try:
                if len(cell_text) == 10:
    >               ret = datetime.datetime.strptime(cell_text, "%Y-%m-%d")
    E               KeyError: '_strptime'

    /usr/local/lib/python3.6/site-packages/pyexcel_io/service.py:31: KeyError

I've the following code installed:

    $ pip show pyexcel
    Name: pyexcel
    Version: 0.5.13
    Summary: A wrapper library that provides one API to read, manipulate and writedata in different excel formats
    Home-page: https://github.com/pyexcel/pyexcel
    Author: C.W.
    Author-email: wangc_2011@hotmail.com
    License: New BSD
    Location: /usr/local/lib/python3.6/site-packages
    Requires: texttable, lml, pyexcel-io
    Required-by: wc-utils

    $ python --version
    Python 3.6.5

I'm unable to reproduce the problem at the command line:

    $ python
    Python 3.6.5 (default, Sep 14 2018, 14:56:31) 
    [GCC 7.3.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import datetime
    >>> d = '1900-01-01'
    >>> datetime.datetime.strptime(d, "%Y-%m-%d")
    datetime.datetime(1900, 1, 1, 0, 0)
    >>> print(datetime.datetime.strptime(d, "%Y-%m-%d"))
    1900-01-01 00:00:00
    >>> d = 'References'
    >>> print(datetime.datetime.strptime(d, "%Y-%m-%d"))
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
        tt, fraction = _strptime(data_string, format)
      File "/usr/local/lib/python3.6/_strptime.py", line 362, in _strptime
        (data_string, format))
    ValueError: time data 'References' does not match format '%Y-%m-%d'

Any ideas? Might pyexcel be using a different datetime? 

Thanks
Arthur

**Comment by artgoldberg** [comment]
Actually, it's tsv data, but I doubt that matters.

**Comment by chfw** [comment]
IMO no, see here: https://github.com/pyexcel/pyexcel-io/blob/dev/pyexcel_io/service.py#L12.

but the KeyError is interesting though. _strptime looks like coming from python itself.

**Comment by artgoldberg** [comment]
You're right, the KeyError comes from Python and is not related to pyexcel. I'm using importlib.import_module() to load some modules, and that appears to create a side-effect in Python that causes datetime.datetime.strptime() to raise "KeyError: '_strptime'" which which is very likely caused by an 'import _strptime' statement in datetime.py. The work-around is to import _strptime in advance.

Arthur
