### ISSUE TITLE
not able to use PyInstaller to distribute

### ISSUE THREAD

**Issue by coooooooorey** [pyexcel/pyexcel#181]
After PyInstaller packing

![image](https://user-images.githubusercontent.com/3081374/57285556-09294780-70e6-11e9-9ca8-0cd5c46fa02a.png)

And I have already added the hidden import to the .spec file.

I tried py2.7, py3.4 and py3.6 without any luck.

my whole code file looks like this.
![image](https://user-images.githubusercontent.com/3081374/57285585-1cd4ae00-70e6-11e9-915d-fd901887bdee.png)

this is my spec

![image](https://user-images.githubusercontent.com/3081374/57285383-afc11880-70e5-11e9-9842-9021d82fc961.png)

and I also tried to use this command:
`pyinstaller --onefile --hidden-import pyexcel_io.readers.csvr --hidden-import pyexcel_io.readers.csvz --hidden-import pyexcel_io.readers.tsv --hidden-import pyexcel_io.readers.tsvz --hidden-import pyexcel_io.writers.csvw --hidden-import pyexcel_io.readers.csvz --hidden-import pyexcel_io.readers.tsv --hidden-import pyexcel_io.readers.tsvz --hidden-import pyexcel_io.database.importers.django --hidden-import pyexcel_io.database.importers.sqlalchemy --hidden-import pyexcel_io.database.exporters.django --hidden-import pyexcel_io.database.exporters.sqlalchemy --hidden-import pyexcel_xlsx --hidden-import pyexcel_xlsx.xlsxr --hidden-import pyexcel_xlsx.xlsxw --hidden-import pyexcel_xlsxw --hidden-import pyexcel_xlsxw.xlsxw --hidden-import pyexcel_xls --hidden-import pyexcel_xls.xlsr --hidden-import pyexcel_xls.xlsw --hidden-import pyexcel.plugins.renderers.sqlalchemy --hidden-import pyexcel.plugins.renderers.django --hidden-import pyexcel.plugins.renderers.excel --hidden-import pyexcel.plugins.renderers._texttable --hidden-import pyexcel.plugins.parsers.excel --hidden-import pyexcel.plugins.parsers.sqlalchemy --hidden-import pyexcel.plugins.sources.http --hidden-import pyexcel.plugins.sources.file_input --hidden-import pyexcel.plugins.sources.memory_input --hidden-import pyexcel.plugins.sources.file_output --hidden-import pyexcel.plugins.sources.output_to_memory --hidden-import pyexcel.plugins.sources.pydata.bookdict --hidden-import pyexcel.plugins.sources.pydata.dictsource --hidden-import pyexcel.plugins.sources.pydata.arraysource --hidden-import pyexcel.plugins.sources.pydata.records --hidden-import pyexcel.plugins.sources.django --hidden-import pyexcel.plugins.sources.sqlalchemy --hidden-import pyexcel.plugins.sources.querysets --hidden-import pyexcel_xls.xls`

**Comment by chfw** [comment]
Have you installed pyexcel xls locally before packing

**Comment by coooooooorey** [comment]
yes, i have.
It worked fine  with python command line.

**Comment by coooooooorey** [comment]
so is there any way to let excel2table.exe  run without a python env ? 😭

**Comment by coooooooorey** [comment]
anyway, I still think pyexcel-handsontable is the best solution~
: (

**Comment by chfw** [comment]
I guess you may have missed python related dll.

**Comment by chfw** [comment]
try ask for help in pyinstaller community?

**Comment by coooooooorey** [comment]
thanks for your time. 🍰

**Comment by coooooooorey** [comment]
`pyinstaller.exe -F .\excel2html.py --hidden-import pyexcel_io.readers.csvr --hidden-import pyexcel_io.readers.csvz --hidden-import pyexcel_io.readers.tsv --hidden-import pyexcel_io.readers.tsvz --hidden-import pyexcel_io.writers.csvw --hidden-import pyexcel_io.readers.csvz --hidden-import pyexcel_io.readers.tsv --hidden-import pyexcel_io.readers.tsvz --hidden-import pyexcel_io.database.importers.django --hidden-import pyexcel_io.database.importers.sqlalchemy --hidden-import pyexcel_io.database.exporters.django --hidden-import pyexcel_io.database.exporters.sqlalchemy --hidden-import pyexcel_xls --hidden-import pyexcel_xls.xlsr --hidden-import pyexcel_xls.xlsw --hidden-import pyexcel.plugins.sources.file_input  --hidden-import pyexcel.plugins.sources.file_output --hidden-import pyexcel.plugins.renderers.excel --hidden-import pyexcel.plugins.parsers.excel --hidden-import pyexcel_handsontable --hidden-import pyexcel_cli  --hidden-import pyexcel_handsontable.handsontable --hidden-import pyexcel.plugins.sources.pydata.arraysource --add-data "pyexcel_handsontable/templates;pyexcel_handsontable/templates"
`

**Comment by coooooooorey** [comment]
Thanks for your project.

Would you please provide a Paypal account for receiving support~?

**Comment by chfw** [comment]
I am glad that my projects helped you. 

My paypal account is: wangc_2011@hotmail.com, or you may choose to become my [Patron](https://www.patreon.com/bePatron?c=830342)

**Comment by chfw** [comment]
Thanks for your support!
