### ISSUE TITLE
where I can find the definition of 'dest_file_stream' parameter in pyexcel.save_as function ?

### ISSUE THREAD

**Issue by lubocheng** [pyexcel/pyexcel#187]
I searched Google and find that, there is someone using `dest_file_stream` as below, but I can't find the parameter definition anywhere, so does it was discarded ?
```python
output_bytes_io = BytesIO()
pyexcel.save_as(
       records=records,
       dest_file_type=self.ext,
       dest_file_stream=output_bytes_io)
```

**Comment by chfw** [comment]
@lubocheng , I am sorry about that. I was facing the challenge to name the parameters where all parameters are virtually the same when reading data from and saving data to an excel file source. Hence, I invented dynamic parameters dest_*, which will be striped out as *. by _split_keywords.

The code line is here:
https://github.com/pyexcel/pyexcel/blob/dev/pyexcel/core.py#L72

**Comment by lubocheng** [comment]
@chfw Many thanks, then we can close this issue now
