### ISSUE TITLE
why get the error?!

### ISSUE THREAD

**Issue by flyfreeme** [pyexcel/pyexcel#188]
file content
import pyexcel
sheet = pyexcel.get_book(file_name="D:/PycharmProjects/tornado_cms/测试.xlsx")
print(sheet)

(venv) D:\venv\Scripts>ipython --gui=qt
Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.8.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %run "e:/pyexcel.py"
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
e:\pyexcel.py in <module>
----> 1 import pyexcel
      2 sheet = pyexcel.get_book(file_name="D:/PycharmProjects/tornado_cms/测试.xlsx")
      3 print(sheet)

e:\pyexcel.py in <module>
      1 import pyexcel
----> 2 sheet = pyexcel.get_book(file_name="D:/PycharmProjects/tornado_cms/测试.xlsx")
      3 print(sheet)

AttributeError: module 'pyexcel' has no attribute 'get_book'

In [2]: import pyexcel

In [3]: %run "e:/pyexcel.py"
Sheet1:

**Comment by chfw** [comment]
Because you named your script as pyexcel. Any other name you can choose?

**Comment by flyfreeme** [comment]
thank you！
