### ISSUE TITLE
Updating Excel file using records

### ISSUE THREAD

**Issue by doudz** [pyexcel/pyexcel#189]
I'm not sure if it's a issue or not but I can't figure how I can update sheet row using records mode

The following code doesn't work, sheet and book are not updated
```
book = pyexcel.get_book(file_name='sample.xls')
sheet = book['Sheet1']
sheet.name_columns_by_row(0)
for row in sheet.get_records():
    row['MyHeader'] = 'test'
book.save_as('sample_mod.xls')
```

**Comment by doudz** [comment]
ok, so if I understand your code, `records` will be updated with the changes but not `sheet` and `book` ?

What I want to do is be able to update a `sheet` in a `book` with many sheets
So, following your example, is the following code the right way ?

```
book = pyexcel.get_book(file_name='sample.xls')
sheet = book['Sheet1']
sheet.name_columns_by_row(0)
records = sheet.get_records()
for row in records:
    row['MyHeader'] = 'test'

del book['Sheet1']
sheet = pyexcel.get_sheet(records=records)
sheet.name = 'Sheet1'
book = book + sheet
book.save_as('sample_mod.xls')
```

**Comment by chfw** [comment]
It looks right to me! But be aware that pyexcel has its limitation: formula, style, fonts, images are not transferred.

**Comment by doudz** [comment]
ok many thanks @chfw !
