### ISSUE TITLE
Convert ODS to CSV: One empty column is added at the right

### ISSUE THREAD

**Issue by mvdw** [pyexcel/pyexcel#19]
I tried the following code to convert a ods with python 2.7:

```
python
import pyexcel as pe
import pyexcel.ext.ods3
pyexcel.save_as(file_name=args.source, dest_file_name=args.destination)
```

The result has the following problem:

One empty column is added at the right. 

This problem can be worked around as follows:
```
sheet = pe.get_sheet(file_name=args.source)
sheet.name_columns_by_row(0)
del sheet.column[""]
sheet.save_as(args.destination)
```
But why was this column there?

**Comment by chfw** [comment]
Let's rule out this is not related to https://github.com/chfw/pyexcel-io/issues/4

Are you having pyexcel-io >=0.0.8? https://github.com/chfw/pyexcel-io/releases/tag/v0.0.8

**Comment by mvdw** [comment]
```
michiel@Janus:~> pip2 freeze | grep pyexcel
Warning: cannot find svn location for rst2pdf==0.93.dev-r0
pyexcel==0.1.7
pyexcel-io==0.0.9
pyexcel-ods==0.0.12
pyexcel-ods3==0.0.10
michiel@Janus:~> pip3 freeze | grep pyexcel
pyexcel==0.1.7
pyexcel-io==0.0.8
pyexcel-ods3==0.0.8
michiel@Janus:~> python --version
Python 2.7.8
michiel@Janus:~> python3 --version
Python 3.4.1
michiel@Janus:~> 
```
The one but last command shows that I am using python 2.7 as default.

**Comment by chfw** [comment]
Hence, I think you have this kind of data:

    >>> data=[
    ... ['A','B','','C','D'],
    ... [1,2,1,3,4]
    ... ]
    >>> import pyexcel
    >>> sheet=pyexcel.Sheet(data)
    >>> sheet.name_columns_by_row(0)
    >>> sheet.column['']
    [1]

Without looking at your input, I could only think of the example case.

**Comment by chfw** [comment]
Please try again with `pip install pyexcel-ods==0.0.12`
