### ISSUE TITLE
sheet.column is empty

### ISSUE THREAD

**Issue by jangxx** [pyexcel/pyexcel#197]
I am creating a new, empty sheet like this:

```python
import pyexcel
sheet = pyexcel.get_sheet(colnames=[ "a", "b", "c", "", "d" ], array=[])
```

I was now expecting to be able to insert data like this:

```python
sheet.column["b"] = [ 1, 2, 3 ]
```

but this always throws an index out of range error. Looking at `sheet.column` with `print(list(sheet.column))` reveals the property to be an empty list. Is this the correct behavior? If if is, then how am I supposed to add data to the sheet?

**Comment by chfw** [comment]
it is not supported to create new column but to overwrite the column which exists already. In this regard, pandas is much more powerful. 

One of many cumbersome ways to make it happen with pyexcel.Sheet, you can do this:

```
>>> import pyexcel as pe
>>> sheet = pe.Sheet()
>>> sheet.row += [ "a", "b", "c", "", "d" ]
>>> sheet
pyexcel sheet:
+---+---+---+---+---+
| a | b | c |   | d |
+---+---+---+---+---+
>>> sheet.paste((1,1), columns=[[ 1, 2, 3 ]])
Traceback (most recent call last):
    raise IndexError(constants.MESSAGE_INDEX_OUT_OF_RANGE)
IndexError: Index out of range
>>> sheet.row += [''] * 5
>>> sheet
pyexcel sheet:
+---+---+---+---+---+
| a | b | c |   | d |
+---+---+---+---+---+
|   |   |   |   |   |
+---+---+---+---+---+
>>> sheet.paste((1,1), columns=[[ 1, 2, 3 ]])
>>> sheet
pyexcel sheet:
+---+---+---+---+---+
| a | b | c |   | d |
+---+---+---+---+---+
|   | 1 |   |   |   |
+---+---+---+---+---+
|   | 2 |   |   |   |
+---+---+---+---+---+
|   | 3 |   |   |   |
+---+---+---+---+---+

```

**Comment by chfw** [comment]
alternatively, you can do:

```
>>> import pyexcel as pe
>>> s = pe.Sheet()
>>> s.row += ['a', 'c', '', 'd']
>>> s.column += ['b', 1,2,3]
>>> s
pyexcel sheet:
+---+---+---+---+---+
| a | c |   | d | b |
+---+---+---+---+---+
|   |   |   |   | 1 |
+---+---+---+---+---+
|   |   |   |   | 2 |
+---+---+---+---+---+
|   |   |   |   | 3 |
+---+---+---+---+---+
```

**Comment by jangxx** [comment]
Thank you for the information. I have now decided to use openpyxl instead of pyexcel for my project, since I really only need it to generate some sheets from scratch and if pyexcel is not built for that application, it's not the right library for my project. Thanks again though.

**Comment by chfw** [comment]
yep, pyexcel is mainly for transcoding and simple information computation task. What pyexcel takes away from a developer, is the chore to put python data structures into excel files and vice versa. For complex computation, you would prefer pandas. For complex style manipulations, you would go for openpyxl.
