### ISSUE TITLE
Merged cell aren't processed properly?

### ISSUE THREAD

**Issue by Lepiloff** [pyexcel/pyexcel#206]
For processing an excel file library openpyxl is used, I need to identify the merged cell. To do this, I call the function `merged_cell_ranges`. 

    workbook = load_workbook(filename=file)
    sheet = workbook["RFI"]
    # get the list of first cell of merged cell coordinate
    list_of_first_coordinate_in_merget_cell = [cell.__str__().split(':')[0] for cell in sheet.merged_cell_ranges]
    for range_ in sheet.merged_cell_ranges:
        # get current coordinate from all merget cell and set it as a string
        cell_obj_to_str = (range_.__str__())
        .....

Work fine for **xlsx**. 
In the project, I need to work with two formats - `xls` and xlsx. 
I convert from xls to xlsx  using **pyexcel** this way 

     if filename.endswith('.xls'):
        import pyexcel
        _f, _ = filename.split('.')
        pyexcel.save_book_as(file_name=file, dest_file_name=f'{_f}.xlsx')

Сonverts everything successfully, openpyxl works with the new file without errors, performs requests and returns all the necessary information. The only problem is that a `merged_cell_ranges` call returns an empty result. 
When opened in the excel editor, I can see that all merged cells are in their places. I don't understand why it doesn't give the result. It looks like some information is lost in the conversion process. Maybe there are thoughts ?

**Comment by chfw** [comment]
I suppose the problem you are finding is: merged cells in xls are not transferred to xlsx file as merged cells.

**Comment by Lepiloff** [comment]
I think so, but that the reason? Bug in library conversion functionality?

**Comment by chfw** [comment]
Well, I am afraid it is an assumed feature of the conversion. It is not likely to get the support soon.

In order to know which cell were merged, a certain notation needed to be passed. As of now, pyexcel uses pure python dictionary to transfer data content between plugins. 

So it will require pyexcel to upgrade interconnection interface to include merge cells alike annotations.
