### ISSUE TITLE
Transferring styles during conversion from xls to xlsx

### ISSUE THREAD

**Issue by Lepiloff** [pyexcel/pyexcel#207]
I convert from xls to xlsx using pyexcel this way

```
 if filename.endswith('.xls'):
    import pyexcel
    _f, _ = filename.split('.')
    pyexcel.save_book_as(file_name=file, dest_file_name=f'{_f}.xlsx')
```

Then I try to get information about the color of the cell

```
def test_excel_file_response(file):
    pc_coordinate = {}
    workbook = load_workbook(filename=file)
    sheet = workbook["RFI"]
    for row_cells in sheet.iter_rows(min_row=4):
        for cell in row_cells:
            if cell.value in paren_category_ and cell.fill.start_color.rgb:
                pc_coordinate[cell.value] = cell.coordinate
                print(cell.value, cell.fill.start_color)
    return pc_coordinate
```

And get Parameters:
`rgb='00000000', indexed=None, auto=None, theme=None, tint=0.0, type='rgb'`

But when I open a file in the editor, I see that the cells are colored. 
Is it the same problem with style transfer as  https://github.com/pyexcel/pyexcel/issues/206  ?

**Comment by chfw** [comment]
Well, yes I am afraid.

```
Known constraints

Fonts, colors and charts are not supported.
```

**Comment by chfw** [comment]
for the time with pyexcel, the focus have been put on the information it contained

**Comment by Lepiloff** [comment]
Okay, thanks for the answer. Anyway, it's the most convenient way for me to convert the file formats

**Comment by chfw** [comment]
Thanks. Let me find the time to turn around to look at it.

**Comment by snoopyjc** [comment]
Hi Lepiloff.  My xls2xlsx package will convert the files and copy the styles.  See https://github.com/snoopyjc/xls2xlsx
