### ISSUE TITLE
Support for hidden sheets

### ISSUE THREAD

**Issue by haydenflinner** [pyexcel/pyexcel#21]
I was just wondering if support for hidden sheets was included or planned in pyexcel. I did a search on the source code for "hidden" and found nothing. Thanks!

**Comment by chfw** [comment]
Have you tried pyexcel on an excel sheet that has hidden sheet(s) yet? And does it read out your hidden sheet(s)? Here is a piece of test code:

    import pyexcel
    import pyexcel.ext.xls # or import the plugin that reads your excel file
    book = pyexcel.get_book(file_name="your_excel.xls")
    print(book)

**Comment by haydenflinner** [comment]
Yes, it reads out the hidden sheets. It's actually how I discovered that Excel has hidden sheets! I think it would be handy though if sheets had a property that told you if they were hidden or not. I wouldn't mind implementing it if I were pointed in the right direction.

**Comment by chfw** [comment]
This is library dependent and I haven't checked all if such is supported. xlrd give its visibility status:

    >>> import xlrd
    >>> wb=xlrd.open_workbook('sample-data.xls')
    >>> s=wb.sheet_by_index(1)
    >>> dir(s)
    ['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_cell_attr_to_xfx', '_cell_types', '_cell_values', '_cell_xf_indexes', '_dimncols', '_dimnrows', '_first_full_rowx', '_ixfe', '_maxdatacolx', '_maxdatarowx', '_position', '_repr_these', '_xf_index_stats', '_xf_index_to_xl_type_map', 'automatic_grid_line_colour', 'bf', 'biff_version', 'book', 'bt', 'cached_normal_view_mag_factor', 'cached_page_break_preview_mag_factor', 'cell', 'cell_note_map', 'cell_type', 'cell_value', 'cell_xf_index', 'col', 'col_label_ranges', 'col_slice', 'col_types', 'col_values', 'colinfo_map', 'columns_from_right_to_left', 'computed_column_width', 'cooked_normal_view_mag_factor', 'cooked_page_break_preview_mag_factor', 'default_additional_space_above', 'default_additional_space_below', 'default_row_height', 'default_row_height_mismatch', 'default_row_hidden', 'defcolwidth', 'dump', 'fake_XF_from_BIFF20_cell_attr', 'first_visible_colx', 'first_visible_rowx', 'fixed_BIFF2_xfindex', 'formatting_info', 'gcw', 'get_rows', 'gridline_colour_index', 'gridline_colour_rgb', 'handle_feat11', 'handle_hlink', 'handle_msodrawingetc', 'handle_note', 'handle_obj', 'handle_quicktip', 'handle_txo', 'has_pane_record', 'horizontal_page_breaks', 'horz_split_first_visible', 'horz_split_pos', 'hyperlink_list', 'hyperlink_map', 'insert_new_BIFF20_xf', 'logfile', 'merged_cells', 'name', 'ncols', 'nrows', 'number', 'panes_are_frozen', 'put_cell', 'put_cell_ragged', 'put_cell_unragged', 'ragged_rows', 'read', 'remove_splits_if_pane_freeze_is_removed', 'req_fmt_info', 'rich_text_runlist_map', 'row', 'row_label_ranges', 'row_len', 'row_slice', 'row_types', 'row_values', 'rowinfo_map', 'scl_mag_factor', 'sheet_selected', 'sheet_visible', 'show_formulas', 'show_grid_lines', 'show_in_page_break_preview', 'show_outline_symbols', 'show_sheet_headers', 'show_zero_values', 'split_active_pane', 'standardwidth', 'string_record_contents', 'tidy_dimensions', 'update_cooked_mag_factors', 'utter_max_cols', 'utter_max_rows', 'verbosity', 'vert_split_first_visible', 'vert_split_pos', 'vertical_page_breaks', 'visibility']
    >>> s.sheet_visible
    0

However, I wondered what's use case of hidden sheet in the context of processing excel file as data. Don't we want the data visible so that they can be processed?

**Comment by haydenflinner** [comment]
In my case, I am writing a script that verifies that a certain format is
being followed across a series of spreadsheets. I found a hidden sheet that
violates the format, but since the end goal is to print out these sheets,
the hidden sheet can be safely ignored. Currently, I've just ignored that
sheet by name, but I think it would be nice to be able to ignore hidden
sheets.

**Comment by chfw** [comment]
I see the need. I will need to do a bit of feasibility study on openxl, odfpy and ezodf before it can be scheduled for next development. xlrd passed in this case.

**Comment by haydenflinner** [comment]
While you're looking at that, are hidden rows much different? I just ran into the same problem but with hidden rows while extending the script that caused the initial issue!

**Comment by chfw** [comment]
Columns can be hidden as well. Let me come back to this after I have released pyexcel-io 0.2.0.

**Comment by chfw** [comment]
For the time being, pyexcel-xls and pyexcel-xlsx would support not reading hidden sheets without being told to. For ods format, such a feature is not going to be delivered any time soon because the existing libraries(ezodf, odfpy) do not support it right away.

Hence, I am closing this ticket as what could be done is done.  When time is right, let's revisit ods' hidden sheet.
