### ISSUE TITLE
CSV UTF-8 encoding

### ISSUE THREAD

**Issue by dasdachs** [pyexcel/pyexcel#22]
Hi!

First of great package, thank you!

I  encountered a problem with csv UTF-8 encoding when converting a xlsx file to csv.

If I follow the recommended way from the docs:

    import pyexcel
    import pyexcel.ext.xlsx

    pyexcel.save_as(file_name="example.xlsx", dest_file_name="exmaple.csv")

and the xlsx file is UTF-8, the dest_file is not. Even if I add `encoding="UTF-8"` nothing changes.

The only workaround I found is to use the CSV standard library:

    import csv
    import pyexcel
    import pyexcel.ext.xlsx

    sheet = pe.get_sheet(file_name="example.xlsx")
    with open("example.csv", "w", newline="", encoding="UTF-8") as csvfile:
        writer = csv.writer(csvfile)
        for row in sheet:
            writer.writerow(row)
        csvfile.close()

**Comment by chfw** [comment]
Hi, please try this:

    import pyexcel
    import pyexcel.ext.xlsx

    pyexcel.save_as(file_name="example.xlsx",
                               dest_file_name="exmaple.csv",
                               dest_encoding="UTF-8") # <--

The related documentation is here but I could have made it more eye-catching. And the similiar issue has been raised from this one: https://github.com/pyexcel/pyexcel/issues/17

**Comment by chfw** [comment]
Here is the documentation on it but I was lazy to publish it to pypi: https://github.com/pyexcel/pyexcel/blob/master/pyexcel/sources/__init__.py#L262

**Comment by dasdachs** [comment]
Despite being published on Pypi, I tried that as well, sorry haven't mention it. It gives me the same result.

**Comment by chfw** [comment]
Do you mean --> dest_encoding="UTF-8" in save_as <-- give you the same result as you use custom csv module?

**Comment by dasdachs** [comment]
No, the same as if I don't declare the encoding at all. Can you replicate the problem?

**Comment by chfw** [comment]
I cannot reproduce it here.

[test.xlsx](https://github.com/pyexcel/pyexcel/files/146599/test.xlsx)

With that test csv, I believe I got utf-8 in the result test.csv.

    import pyexcel
    import pyexcel.ext.xlsx

    pyexcel.save_as(file_name="test.xlsx", dest_file_name="test.csv", dest_encoding="UTF-8")


![test csv](https://cloud.githubusercontent.com/assets/4280312/13321781/05dcf2d0-dbc9-11e5-843b-c55b6c63f1ed.png)

Here's reference to unicode dictionary for 'e4 b8 ad': http://www.utf8-chartable.de/unicode-utf8-table.pl?start=19904&number=128

**Comment by dasdachs** [comment]
Now just to avoid public humiliation, I am using Python 3.4.

When I run the code with the test file you provided, i get
  
     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode characters in position 2-5: character maps to <undefined>

I am starting to believe that this has to do something with windows.

**Comment by chfw** [comment]
I tried it with python 2.7. When I get a chance, I will try it with python 3.

**Comment by dasdachs** [comment]
With Python 2.7 my workaround does not work (would have to adapt it), while the code you provided works perfectly. So we are down to Python 3. I'd love to help, just let me know.

**Comment by chfw** [comment]
I tried again with python 3.4 on windows and cannot reproduce it. So, I guess there is something wrong with your python setup.

![py3 4](https://cloud.githubusercontent.com/assets/4280312/13337618/6af5d042-dc14-11e5-9a2a-b58fe458ad75.PNG)

**Comment by dasdachs** [comment]
It might not be my setup, but a bug: [Issue1602 ](http://bugs.python.org/issue1602).

I have tried several workarounds and spent some hours in pyexcels and openpyxl's source code, but I am not sure what to do... Yet, that is.

It has to do with passed keywords when reading a file and has to be something that changed with Python 3. But since .xlsx files are loaded vie openpyxl.load_workbook, I'll have to dig into that part. Am I correct?

**Comment by chfw** [comment]
The issue was reported for Python 3.5.

Can you share your full stack trace?

**Comment by dasdachs** [comment]
Well it's not unheard of in previous versions. I came across it while reading this in [Stackoverflow](http://stackoverflow.com/questions/878972/windows-cmd-encoding-change-causes-python-crash/3259271).

![save_as_error](https://cloud.githubusercontent.com/assets/12150735/13349484/7570af04-dc7a-11e5-970c-0a47cd4c4e13.JPG)

Same thing happens if I change chcp to 65001, so this is not the solution. The solution, at least for me, was to `open('test.csv', 'w', encoding='utf=8')` and pass the rows from `pyexcel.get_sheet object('test.xlsx')`. So the issue is probably easy to fix, I just haven't figured out how.

**Comment by chfw** [comment]
The quick fix for your case is to modify https://github.com/pyexcel/pyexcel-io/blob/master/pyexcel_io/csvbook.py#L225 like this:

     self.f = open(file_name, "w", newline="", encoding='utf-8')

And you can apply the ad-hoc change by editing C:\Users\Tina\venv\excel\venv\lib\site-packages\pyexcel_io\csvbook.py.

I will need to read a bit more around this.

**Comment by dasdachs** [comment]
You are amazing for al your effort you put into it. I'll try my best to assist you in any way I can. 

Your proposed workaround helps, but it is a CMD or at least a Windows problem.

If I open my output (with your workaround or mine) in say Notepad++, it displays correctly, if type:

    type test.csv

in the command line, the output is bad. It helps when I do `chcp 65001` but the output is still not completely correct.

Anyways, thank you!

**Comment by chfw** [comment]
pyexcel-io v0.2.1 may have fixed [some utf-8 encoding problem](https://github.com/pyexcel/pyexcel-io/blob/master/CHANGELOG.rst#021---11072016). You may have a look.

**Comment by dasdachs** [comment]
Thank you. I'll get to it tomorow and will let you know.

Cheers, Jani

V čet., 4. avg. 2016 13.33 je oseba jaska <notifications@github.com>
napisala:

**Comment by dasdachs** [comment]
Still the same problem. It must be a Windows thing. I'll do some more testing in OS X and Ubuntu to confirm that.

Thank your for your incredible work!

**Comment by bmeredyk** [comment]
Sadly, this still seems to be an issue on Windows & python 2.7

  File "C:\Python27\lib\site-packages\pyexcel\sheets\sheet.py", line 445, in save_as
    **keywords)
  File "C:\Python27\lib\site-packages\pyexcel\sources\__init__.py", line 38, in save_sheet
    return _save_any(source, sheet)
  File "C:\Python27\lib\site-packages\pyexcel\sources\__init__.py", line 50, in _save_any
    source.write_data(instance)
  File "C:\Python27\lib\site-packages\pyexcel\sources\file_source_output.py", line 48, in write_data
    sheet, **self._keywords)
  File "C:\Python27\lib\site-packages\pyexcel\renderers\_excel.py", line 22, in render_sheet_to_file
    save_data(file_name, data, **keywords)
  File "C:\Python27\lib\site-packages\pyexcel_io\io.py", line 85, in save_data
    **keywords)
  File "C:\Python27\lib\site-packages\pyexcel_io\io.py", line 106, in store_data
    writer.write(data)
  File "C:\Python27\lib\site-packages\pyexcel_io\book.py", line 163, in write
    sheet_writer.write_array(incoming_dict[sheet_name])
  File "C:\Python27\lib\site-packages\pyexcel_io\sheet.py", line 158, in write_array
    self.write_row(row)
  File "C:\Python27\lib\site-packages\pyexcel_io\fileformat\_csv.py", line 173, in write_row
    self.writer.writerow(array)
  File "C:\Python27\lib\site-packages\pyexcel_io\fileformat\_csv.py", line 60, in writerow
    for s in row])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8: ordinal not in range(128)
