### ISSUE TITLE
ValueError when trying to save to xlsx

### ISSUE THREAD

**Issue by hiphamster** [pyexcel/pyexcel#222]
Hi,

Is there a way to force string conversion on data that can't be directly converted to excel?  (Similar to how it's done with csv)

~~~pre
{   '_links': { 'collection': '/api/v1.0/services',
                'self': '/api/v1.0/services/10'},
    '_resource': 'service',
    'comments': None,
    'id': 10,
    'name': 'Other',
    'period': 'D',
    'period_multiple': 0
}
~~~

the `links` value causes a ValueError, when converting to excel, and is converted to string, when converting to csv:

~~~
| {"self": "/api/v1.0/services/10", "collection": "/api/v1.0/services"} | service   |          | 10 | Other         | D      | 0               |
~~~

Thank you!

**Comment by chfw** [comment]
could I have your exception traceback?

**Comment by chfw** [comment]
I would suggest that you would format it as string, in a 'white box' mode, because if pyexcel-xlsx handle it as a 'black box', it will be very slow.
