### ISSUE TITLE
Get dictionary the content of a specific sheet in multiple sheet

### ISSUE THREAD

**Issue by kingdg25** [pyexcel/pyexcel#223]
By using pyexcel.get_book_dict(), it gets the sheets in dictionary format.
Like 
```>>> book = pyexcel.get_book(file_name="output.xls")
>>> sheets = book.to_dict()
>>> for name in sheets.keys():
...     print(name)
Sheet 1
Sheet 2
Sheet 3
```

then now i want to get the content of Sheet 1 as dictionary. 
But it show a 2D array(list) of data 
example
```
Sheet 1: [[X,Y,Z],[1,2,3],[1,2,3]]
```
. How can I convert the 2D array to dictionary like
```
Sheet 1:
[
    {
        X: 1,
        Y: 2,
        Z: 3
    },
    {
        X: 1,
        Y: 2,
        Z: 3
    }
]
```
my current pyexcel version is
`pyexcel 0.5.15`

Thanks,
Kingie

**Comment by chfw** [comment]
Try this:

```
import pyexcel as p
records = p.get_records(file_name='your_bool.xls', sheet_name='Sheet 1')
print(recrods)
```

**Comment by chfw** [comment]
here are the api reference: http://docs.pyexcel.org/en/latest/api.html
