### ISSUE TITLE
`get_sheet(records=...)` ignore new columns

### ISSUE THREAD

**Issue by NatureGeorge** [pyexcel/pyexcel#224]
Appreciate your perfect work.

## Issue

I am implementing `pyexcel.get_sheet` to load a list of dictionary into the `Sheet`. Although the code could handle missing values for existing columns, it seems to create the sheet with the first dictionary and ignore new columns/keys:

## Reproduce

```python
In [1]: from pyexcel import get_sheet

In [2]: sheet = get_sheet(records=[{'1': 'A', '2': 'B', '4': 'D'}, {'1': 'AA', '2': 'BB', '3': 'CC'}])

In [3]: sheet
Out[3]:
pyexcel_sheet1:
+----+----+---+
| 1  | 2  | 4 |
+----+----+---+
| A  | B  | D |
+----+----+---+
| AA | BB |   |
+----+----+---+
```

## Expected Output

```python
+----+----+----+---+
| 1  | 2  | 3  | 4 |
+----+----+----+---+
| A  | B  |    | D |
+----+----+----+---+
| AA | BB | CC |   |
+----+----+----+---+
```

## Question

Solutions might be specifying all the possible keys in the first dictionary. However, I can't know all the possible columns in advance in my use case. And I am wondering whether `pyexcel` has other interfaces to deal with this issue.

**Comment by chfw** [comment]
for performance concerns, it assumed all keys are uniform( all records have the same key). Hence the implementation used the keys of the first record as the keys for all.

**Comment by chfw** [comment]
so, your problem needs two pass: one pass is to get all possible columns and second pass is what you are doing. either your program or pyexcel.

**Comment by NatureGeorge** [comment]
It seems to be solved like this (for small datasets):

```python
records: Iterable[Dict] = list(records)
keys = {key for record in records for key in record.keys()}
head = records[0]
records[0] = {key: head.get(key, None) for key in keys}
sheet = get_sheet(records=records)
# sheet.save_as('...')
```

Digesting the entire `records` is a necessary procedure. I understand that it is also inevitable for methods like `get_sheet`  to load all the data in memory.

My original requirement in my usage was that, load dictionaries from a geneator and transform it into a tabular format (i.e CSV, TSV) and save them in the disk. The trouble is, as mentioned, each dictionary has a different set of keys. For a larger dataset, the memory raises a new issue.

Re-constructing those dictionaries after receiving them might be the key. Thanks for your reply!

**Comment by chfw** [comment]
for large datasets, we have to know explicitly the columns first. Then we can stream the data from input to output.

**Comment by NatureGeorge** [comment]
Got it. 👌
