### ISSUE TITLE
XLS/XLSX/ODS to CSV discards empty columns at the end of row

### ISSUE THREAD

**Issue by kaittodesk** [pyexcel/pyexcel#228]
Let's assume I have created a XLSX file (named `source.xlsx`) with following data:

| | **A** | **B** | **C** |
|---|---|---|---|
| **1** | Foo | | |
| **2** | Bar | 18 | Student |
| **3** | Baz | 43 | |

and use `pyexcel` to convert created XLSX file to CSV using following snippet:

```python
with open('source.xlsx', 'rb') as fh:
        pyexcel.isave_as(file_stream=fh, file_type='xls', dest_file_name='target.csv', encoding='utf-8')
```

I end up getting following CSV file:

```
Foo
Bar,18,Student
Baz,43
```

But I am expecting to get CSV file with following structure:

```
Foo,,
Bar,18,Student
Baz,43,
```
(to clarify first row is missing column B and C; and third is missing column C).

This happens with XLS (Excel 97-2003), XLSX (Excel 2007-365) and ODS (ODF Spreadsheet) file formats.

I am using Python 3.7.9 and following packages:
```
pyexcel==0.6.4
pyexcel-io==0.5.20
pyexcel-ods==0.5.6
pyexcel-xls==0.5.9
```

**Comment by chfw** [comment]
Agreed. And this is going to change soon:  to keep empty columns at the end, do this: get_data(...keep_trailing_empty_cells=True)

https://github.com/pyexcel/pyexcel-io/issues/86

so once pyexcel-io v0.6.0 is released, you will be able to use it across all pyexcel plugins.

You can try it now if you wish:

`$ pip install https://github.com/pyexcel/pyexcel-io/archive/dev.zip`

**Comment by kaittodesk** [comment]
Thank you for your prompt and helpful reply.

Yes, with (soon to be) `pyexcel-io==0.6.0` and `keep_trailing_empty_cells=True` I get the expected CSV output.

**Comment by chfw** [comment]
pyexcel-io 0.6.0 was released.
