### ISSUE TITLE
csv columns lost

### ISSUE THREAD

**Issue by jayvdb** [pyexcel/pyexcel#23]
With the latest pypi versions, (0.2.0, io 0.1.0), the following CSV input looses all columns after "ISSN 1"

```csv
ERAID,Title,"Foreign Title","FoR 1","FoR 1 Name","FoR 2","FoR 2 Name","FoR 3","FoR 3 Name","ISSN 1","ISSN 2","ISSN 3","ISSN 4","ISSN 5","ISSN 6","ISSN 7"
125026,306090,,1201,Architecture,,,,,1536-1519,,,,,,,,
```

e.g. converting to html using `text` plugin

```html
Sheet Name: test.csv
<table>
<tbody>
<tr><td>ERAID </td><td>Title </td><td>Foreign Title</td><td>FoR 1</td><td>FoR 1 Name  </td><td>FoR 2</td><td>FoR 2 Name</td><td>FoR 3</td><td>FoR 3 Name</td><td>ISSN 1   </td></tr>
<tr><td>125026</td><td>306090</td><td>             </td><td>1201 </td><td>Architecture</td><td>     </td><td>          </td><td>     </td><td>          </td><td>1536-1519</td></tr>
</tbody>
</table>
```

This bug doesnt affect the latest code in pyexcel and pyexcel-io , however when using master on these repos, the `text` plugin breaks.

**Comment by chfw** [comment]
will look into it.

**Comment by jayvdb** [comment]
My apologies, it seems like this isnt a bug in pyexcel or pyexcel-io.
I thought I tested csv->csv and the same problem occurred, but I've retested that and it works correctly.
fwiw, I am pretty confident that this is a bug in tabulate, at least for my csv -> html conversion.
Reported as https://github.com/pyexcel/pyexcel-text/issues/6
