### ISSUE TITLE
open file from memory in django

### ISSUE THREAD

**Issue by arezazadeh** [pyexcel/pyexcel#239]
Hi, 
when i am trying the below code i get this error:
```
def bulk_upload(request):
    form = UploadForm(request.POST, request.FILES)
    if form.is_valid():
        loc = request.FILES["file_field"]
        file_name = loc.name
        records = pyexcel.get_records(filename=file_name)
```
and this is the error i get:

```

Exception Type: | UnknownParameters
-- | --
Please check if there were typos in function parameters: {'filename': 'inventory_template.xlsx'}. Otherwise unrecognized parameters were given.
```
since django stores the file in memory, i am not sure how to grab it and read it with pyexcel. 

appreciate your help. 
Ahmad.

**Comment by chfw** [comment]
In short, you need to use ‘file_content’ parameter.

Probably you are not aware pyexcel project had a webware project: https://github.com/pyexcel-webwares/django-excel

please either use the code or reference it.

**Comment by arezazadeh** [comment]
awesome thanks so much, i used a different method, i write it into the disk with chunks() then read it from there.

**Comment by chfw** [comment]
Bear in mind, disk io takes time!
