### ISSUE TITLE
How to change column header name for single sheet

### ISSUE THREAD

**Issue by wbashir** [pyexcel/pyexcel#24]
`sheet["Some Column"] = "New Name"` doesn't change the header name?

**Comment by chfw** [comment]
Provided that you have named column by a row, you can do sheet.colnames = new_column_names. Same for rownames.

**Comment by wbashir** [comment]
@chfw  thanks for the quick reply. If `new_column_names` in your example is a list of column names, how will this only update the single column name at row `1`? In other words, I am only looking to update one colname
