### ISSUE TITLE
Load as Decimal

### ISSUE THREAD

**Issue by mortoray** [pyexcel/pyexcel#240]
How can I load excel files using a Decimal type for numbers?

I tried the below, to turn off auto-detect, but it's still loading the values as float/int:

```
records = pyexcel.iget_records(
	file_name=filename,
	auto_detect_float=False,
	auto_detect_int=False,
)
```

**Comment by chfw** [comment]
For some types , those flag are not working because those types are auto detected by underlying lib, I.e. openpyxl.

**Comment by chfw** [comment]
Alternative, you can pass on your custom `row_renderer` to get_data. pyexcel-io will feed each row to your row_renderer, via which you could do the conversion of float to Decimal yourself.

https://github.com/pyexcel/pyexcel-io/blob/dev/pyexcel_io/sheet.py#L93
