### ISSUE TITLE
merge_all_to_a_book drops column headers

### ISSUE THREAD

**Issue by aleksbor** [pyexcel/pyexcel#241]
merge_all_to_a_book(glob.glob("*.csv"),filename.xlsx) removes all the column headers from the CSVs. Please advise.

**Comment by chfw** [comment]
Do you have reproducing case?

**Comment by aleksbor** [comment]
Example:
1.csv
header1,,header3,header4
1,2,3,4
2.csv
headerA,headerB,,headerD
A,,C,D
F,G,M,T
The XLSX output would be:
Sheet - 1.csv
1,2,3,4
Sheet - 2.csv

**Comment by chfw** [comment]
https://github.com/pyexcel/pyexcel/blob/e73b8c7200ef3df03db00a50e2177f7b8e59c9e9/tests/test_bug_fixes.py#L541 
As you read the new test case, your problem can’t be reproduced.
