### ISSUE TITLE
How do you use `dest_initializer` and `dest_model`?

### ISSUE THREAD

**Issue by coler-j** [pyexcel/pyexcel#242]
Having difficulties understanding the documentation for interaction between `dest_initializer` and `dest_model`?

If I have a Django model like:

```
class MyModel(Model)
    file = FileField()
```

How can I write a file to **an instance** of this model?

```
instance = MyModel()

records = [OrderedDict([("Test Key", "Test Value")])]
pyexcel.save_as(
                records=records,
                dest_model=MyModel,
                ...... ?????? How to write to instance.field?
            )
```

Also see https://stackoverflow.com/questions/43396437/processing-excel-data-using-pyexcel

**Comment by coler-j** [comment]
Ah, sorry I figured you could load a file directly into a Django FileField, but it seems like your model attributes need to reflect the shape of you file. So it is more "importing" to Django, versus saving the file to a Django model.

**Comment by chfw** [comment]
yes. that's why you would use django-excel instead of pyexcel directly.
