### ISSUE TITLE
Can't make pyexcel work with pyinstaller

### ISSUE THREAD

**Issue by FlorianGai** [pyexcel/pyexcel#246]
Hello,

I'm trying to build my code using pyinstaller and I tried to use both links below:
- [https://pyexcel.readthedocs.io/en/latest/pyinstaller.html](url)
- [http://io.pyexcel.org/en/latest/pyinstaller.html](url)

Here is the command line I use:

`pyinstaller --onefile --hidden-import pyexcel.plugins.renderers.sqlalchemy --hidden-import pyexcel.plugins.renderers.django --hidden-import pyexcel.plugins.renderers.excel --hidden-import pyexcel.plugins.renderers._texttable --hidden-import pyexcel.plugins.parsers.excel --hidden-import pyexcel.plugins.parsers.sqlalchemy --hidden-import pyexcel.plugins.sources.http --hidden-import pyexcel.plugins.sources.file_input --hidden-import pyexcel.plugins.sources.memory_input --hidden-import pyexcel.plugins.sources.file_output --hidden-import pyexcel.plugins.sources.output_to_memory --hidden-import pyexcel.plugins.sources.pydata.bookdict --hidden-import pyexcel.plugins.sources.pydata.dictsource --hidden-import pyexcel.plugins.sources.pydata.arraysource --hidden-import pyexcel.plugins.sources.pydata.records --hidden-import pyexcel.plugins.sources.django --hidden-import pyexcel.plugins.sources.sqlalchemy --hidden-import pyexcel.plugins.sources.querysets --hidden-import pyexcel_io.readers.csv_in_file --hidden-import pyexcel_io.readers.csv_in_memory --hidden-import pyexcel_io.readers.csv_content --hidden-import pyexcel_io.readers.csvz --hidden-import pyexcel_io.writers.csv_in_file --hidden-import pyexcel_io.writers.csv_in_memory --hidden-import pyexcel_io.writers.csvz_writer --hidden-import pyexcel_io.database.importers.django --hidden-import pyexcel_io.database.importers.sqlalchemy --hidden-import pyexcel_io.database.exporters.django --hidden-import pyexcel_io.database.exporters.sqlalchemy --hidden-import pyexcel_io.readers.csvr --hidden-import pyexcel_io.readers.csvz --hidden-import pyexcel_io.readers.tsv --hidden-import pyexcel_io.readers.tsvz --hidden-import pyexcel_io.writers.csvw --hidden-import pyexcel_io.writers.csvz --hidden-import pyexcel_io.writers.tsv --hidden-import pyexcel_io.writers.tsvz --hidden-import pyexcel_io.database.importers.django --hidden-import pyexcel_io.database.importers.sqlalchemy --hidden-import pyexcel_io.database.exporters.django --hidden-import pyexcel_io.database.exporters.sqlalchemy --hidden-import pyexcel_xlsx --hidden-import pyexcel_xlsx.xlsxr --hidden-import pyexcel_xlsx.xlsxw --hidden-import pyexcel_xls --hidden-import pyexcel_xls.xlsr --hidden-import pyexcel_xls.xlsw main.py`

When I try to execute the part of my code that uses pyexcel, I always get an error message:

> pyexcel_io.exceptions.SupportingPluginAvailableButNotInstalled : Please install one of these plugins for read data in 'xlsx' : pyexcel-xls, pyexcel-xlsx

Please, note that the code works fine when debugging or running from pycharm.

Here are the versions I use:
pyexcel 0.6.6
pyexcel-io 0.6.4
pyexcel-xls 0.6.2
pyexcel-xlsx 0.6.0

Can anyone help me with that issue?

Thanks

**Comment by FlorianGai** [comment]
Turns out I had the wrong pyinstaller version. Works fine now.

**Comment by chfw** [comment]
can you please share the pyinstaller version? is it the latest?
