### ISSUE TITLE
Released version 0.2.0 is not a release/branch in github

### ISSUE THREAD

**Issue by jayvdb** [pyexcel/pyexcel#25]
https://pypi.python.org/pypi/pyexcel is currently 0.2.0 , however there is no corresponding branch or release in github.  

There is only https://github.com/pyexcel/pyexcel/tree/v0.2.0-rc1 , which has [VERSION](https://github.com/pyexcel/pyexcel/blob/v0.2.0-rc1/VERSION) file containing `0.2.0-rc1`

**Comment by jayvdb** [comment]
There is a similar problem exists for -io 0.1.0 , which has a branch for 0.1.x , but the last release was for 0.1.0-rc1

**Comment by jayvdb** [comment]
Same problem with -xlsx 0.1.0

**Comment by chfw** [comment]
For those releases, the git releases were not up to date. I am interested to know your use case for the github releases. I felt boring to do both pypi and github.

**Comment by jayvdb** [comment]
I needed to checkout the released versions so i could debug the problems I have raised and develop new features, because the master versions are not compatible

**Comment by chfw** [comment]
obvious reason. debt paid.
