### ISSUE TITLE
Query sets source

### ISSUE THREAD

**Issue by TimurKady** [pyexcel/pyexcel#252]
Open the great secret, please! Specify query sets source **parameter name**. The documentation contains the phrase _"any query sets (sqlalchemy or django)"_ in the corresponding table. **query_sets** not working.

_**UnknownParameters:** Please check if there were typos in function parameters: {'query_sets': <QuerySet [..._

**Comment by chfw** [comment]
django example: http://django.pyexcel.org/en/latest/#handle-custom-data-export

flask(sqlalchemy) example: http://flask.pyexcel.org/en/latest/#export-filtered-query-sets
