### ISSUE TITLE
Suppressing PyExcel Empty Row Warning during file read to SQLAlclemy model

### ISSUE THREAD

**Issue by avagut** [pyexcel/pyexcel#253]
I am saving the contents of an excel file to a SQLAlchemy DB table using pyexcel as following: `pyexcel.save_as(file_name='my_excel_file.xlsx',` <br> `  
             name_columns_by_row=0,` <br> `                 dest_session=db.session, ` <br> `                dest_table=models.MyModel)`

This is working well and saving the data but it's leaving several log messages that `One empty row is found` in the terminal. How do I suppress these messages to avoid polluting the logs? I know about the empty rows and they have no impact on the data loading
Is there a parameter to pyexcel or to the save as function to suppress these warnings?

**Comment by chfw** [comment]
It seems not possible without a code change. 

https://github.com/pyexcel/pyexcel-io/blob/e40737495bbc4b382b567911c5d6a07670a9af03/pyexcel_io/database/importers/sqlalchemy.py#L38

Let me code it up for you.

**Comment by chfw** [comment]
what I am going to do is to  replace 'print' with a logger.warning. would it work for you?

**Comment by avagut** [comment]
@chfw 
Thank you very much for responding. I didn't know that the message was coming from pyexcel-io as indicated in the referenced link you have shared.
I guess that is why I could not find the error message. This makes everything much clearer.
With this understanding, in the pyexcel docs I found a parameter `skip_empty_rows=True` for when you reading from a source file which I passed to the `pyexcel.save_as` function and this silenced the log messages, so it was exactly what I needed in this use-case. :smiley:
This particular propagation behavior is not indicated in the docs, it would be nice to have it highlighted in there.
I also think a logger.warning would work better so that it shows up in the appropriate logs especially in prod environments.
I very much appreciate all you do for this awesome library!

**Comment by chfw** [comment]
thanks. I will update that line. 

pyexcel-io does the basic input and output. pyexcel does a bit more on abstractions.

**Comment by chfw** [comment]
I was about to add it to the documentation. but it seems `skip_empty_rows` was documented as below:

http://docs.pyexcel.org/en/latest/generated/pyexcel.save_as.html#pyexcel.save_as

I will update here when the new version pyexcel-io is to be released.

**Comment by chfw** [comment]
Checkout pyexcel-io v0.6.6

**Comment by avagut** [comment]
> I was about to add it to the documentation. but it seems `skip_empty_rows` was documented as below:
> 
> http://docs.pyexcel.org/en/latest/generated/pyexcel.save_as.html#pyexcel.save_as
> 
> I will update here when the new version pyexcel-io is to be released.

This is so much clearer, thank you very much!
