### ISSUE TITLE
sheet.column ValueError: 'col2' is not in list

### ISSUE THREAD

**Issue by rez0n** [pyexcel/pyexcel#254]
Hi, according to [docs](http://docs.pyexcel.org/en/latest/tutorial05.html#column-manipulation) to manipulate data on the sheet I can't get a column by its name.

I have a multi-sheet XLSX file, I need to change the data on the second sheet of the book.
```
file_content = open('.dev.nosync/test_book.xlsx', 'rb')
book = pyexcel.get_book(file_stream=file_content, file_type='XLSX',
                            name_columns_by_row=0, skip_hidden_sheets=False)

sheet = book['test2']
print(sheet)

+------+------+
| col1 | col2 |
+------+------+
| 1    | 1    |
+------+------+
| 2    | 2    |
+------+------+
```

On trying to update data in the column I get ValueError.
```
sheet.column["col2"] = [11, 12, 13]
ValueError: 'col2' is not in list
```

Meanwhile 
````
print(sheet.column[1])
>>> ['col2', 1, 2]

print(sheet.column['col2'])
>>> ValueError: 'col2' is not in list
````

Does anybody have ideas about what is wrong?
Thanks in advance.

**Comment by chfw** [comment]
You need to use the function to name column by row.

**Comment by chfw** [comment]
One more note is: `name_columns_by_row=0,` wont work for get_book.

```
pyexcel.get_book(file_stream=file_content, file_type='XLSX',
                            name_columns_by_row=0, skip_hidden_sheets=False)
```
