### ISSUE TITLE
pyexcel.get_array documentation page seems to be a copy of pyexcel.get_sheet

### ISSUE THREAD

**Issue by chimosky** [pyexcel/pyexcel#255]
The [`pyexcel.get_array`](https://docs.pyexcel.org/en/latest/generated/pyexcel.get_array.html) page seems to contain the exact same examples as [`pyexcel.get_sheets`](https://docs.pyexcel.org/en/latest/generated/pyexcel.get_sheet.html#), so on the `get_array` page the function itself is never used.

**Comment by chfw** [comment]
You are right.

just the following line is different : 

It accepts the same parameters as [get_sheet()](https://docs.pyexcel.org/en/latest/generated/pyexcel.get_sheet.html#pyexcel.get_sheet) but return an array instead

**Comment by chfw** [comment]
You are one of the few who reads my api docs.

**Comment by chimosky** [comment]
> You are one of the few who reads my api docs.

As a fellow maintainer I understand the importance of docs and I really wish more people would RTD and I found that out while testing some changes on my day job, keep doing the awesome job you're doing. Thanks!
