### ISSUE TITLE
Add tqdm progressbar to BookStream and SheetStream [feature request]

### ISSUE THREAD

**Issue by root-11** [pyexcel/pyexcel#265]
Would it be possible to add a progress bar ([tqdm](https://github.com/tqdm/tqdm) preferred) to load & save sheet/book?

I often see 400-500Mb xlsx books and it does take a little while to read them.

At a quick glance it seems like a relatively simple wrapping about `get_stream` for load book and sheet near this:

https://github.com/pyexcel/pyexcel/blob/d8b965060889708ed7f718139076a71fe8c25490/pyexcel/internal/core.py#L29

For save I couldn't quite figure the call hierarchy out.

**Comment by chfw** [comment]
You can add tqdm in your application.
