### ISSUE TITLE
CSV : decimal separator

### ISSUE THREAD

**Issue by doudz** [pyexcel/pyexcel#268]
By default in csv format, the float decimal separator is a dot : 1.005
But how can I change it to use comma instead ? : 1,005 

I need it since in France, the official decimal separator is a comma, not a dot...

(of course I use another delimiter ";" )

**Comment by chfw** [comment]
that has to be with your data presentation. pyexcel or csv module are not in control.

**Comment by jgonggrijp** [comment]
May I request that this ticket be reopened. pyexcel is actually in control here, in the sense that it is doing an extra number coercion step beyond what the builtin `csv` module is doing. That extra step is preventing people like me and @doudz, who need to work with decimal commas, from reading the numbers correctly. Consider the following CSV:

```csv
"2023-07-29";"0,02"
```

If I do this:

```py
import csv

with open('the-above-file.csv') as my_file:
    print(next(csv.reader(my_file, delimiter=';')))
```

I get `('2023-07-29', '0,02')` as output. The second field is not interpreted, I can do a string replacement to replace the decimal comma by a decimal point.

However, if I do this:

```py
import pyexcel

print(pyexcel.get_array(file_name='the-above-file.csv', delimiter=';')[0])
```

I get `['2023-07-09', 2]`. The second field has already been interpreted and the position of the decimal comma has been lost.

I can understand if you cannot or don't want to support decimal commas, but at least please give us a way to switch off automatic number coercion so we can address it ourselves. As it currently is, I have to revert to the standard `csv` module.

**Comment by CodeWithOz** [comment]
@jgonggrijp were you using pyexcel's `iget_records` method? If so, how did you replace its functionalty with the standard `csv` module? Asking because I'm using `iget_records` for processing large files without loading them all into memory, so I need a solution that won't blow out my memory if I switch away from pyexcel.

**Comment by jgonggrijp** [comment]
@CodeWithOz I didn't use `iget_records`. I'm fortunate enough that I only need to work with small spreadsheets.
