### ISSUE TITLE
Command line interface

### ISSUE THREAD

**Issue by jayvdb** [pyexcel/pyexcel#27]
It would be nice to have a command line tool that provides easy to use conversion between formats, like https://github.com/peterhil/excelsior provides.

**Comment by chfw** [comment]
Yes, I agree. This can be scheduled in the "road map"(don't have one yet) and can be named "pyexcel-cli", which brings pyexcel to command line interface. 

What command options do you imagine it should have? Its requirements could go ahead.

**Comment by chfw** [comment]
stay tuned here https://github.com/pyexcel/pyexcel-cli

**Comment by jayvdb** [comment]
Thanks.  The features that you've outlined there look great.

I am mostly interested in the trans-coding xlsx to json, and then to sane xml.  The only parameter I am using is `name_columns_by_row=0`, and IMO that could be removed by some smarts inside pyexcel (and maybe it already exists).
https://github.com/jayvdb/era_data/blob/master/fetch.sh#L93

I'd be very happy if the output filename is deduced from the input filename, or the filetype conversion process determined from an input and output file extension. but I wouldnt not be annoyed if I need to supply all those arguments on the command line.

For the actual command line interface, in addition to excelsior mention in the OP, copying [ssconvert](https://help.gnome.org/users/gnumeric/stable/sect-files-ssconvert.html) or [xsx2csv](https://github.com/dilshod/xlsx2csv) or [in2csv](http://csvkit.readthedocs.io/en/latest/scripts/in2csv.html) could be useful in order to be a drop-in replacement.

**Comment by chfw** [comment]
Initial usable command line interface was released. For further improvement, let's continue at pyexcel-cli's issues.

You may update your line as: 

     pyexcel transcode --name-columns-by-row 0 downloads/ERA_2015_Submission_Journal_List.xlsx downloads/ERA2015JournalList.json
