### ISSUE TITLE
No moduled named pyexcel.ext.*

### ISSUE THREAD

**Issue by germanferrero** [pyexcel/pyexcel#28]
Hi, I can't import pyexcel.ext.plugin.
my pip freeze:
decorator==4.0.9
Django==1.8.12
django-constance==1.1.2
et-xmlfile==1.0.1
ipython==4.1.2
ipython-genutils==0.1.0
jdcal==1.2
openpyxl==2.3.4
path.py==8.1.2
pexpect==4.0.1
pickleshare==0.6
ptyprocess==0.5.1
pyexcel==0.2.0
pyexcel-io==0.1.0
redis==2.10.5
simplegeneric==0.8.1
texttable==0.8.4
traitlets==4.2.1
xlrd==0.9.4

`ImportError                               Traceback (most recent call last)
<ipython-input-34-6d5d47bc1018> in <module>()
----> 1 import pyexcel.ext.plugin

/home/gf/.virtualenvs/me-app-env/local/lib/python2.7/site-packages/pyexcel/exthook.pyc in load_module(self, fullname)
    115                 setattr(sys.modules[self.wrapper_module], modname, module)
    116             return module
--> 117         raise ImportError('No module named %s' % fullname)
    118 
    119     def is_important_traceback(self, important_module, tb):

ImportError: No module named pyexcel.ext.plugin
`

**Comment by chfw** [comment]
pyexcel.ext.plugin does not exist as import error tells. all available plugins are found in [pyexcel github page](https://github.com/pyexcel).

**Comment by germanferrero** [comment]
Ok, I got confused with docs.
Can you please help me with csv reading?

`In [46]: import pyexcel

In [47]: import pyexcel_io

In [48]: ls /home/gf/test.csv
/home/gf/test.csv

In [49]: sheet = pyexcel.get_sheet(filename='/home/gf/test.csv')
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-49-d27e706b89c9> in <module>()
----> 1 sheet = pyexcel.get_sheet(filename='/home/gf/test.csv')

/home/gf/.virtualenvs/me-app-env/local/lib/python2.7/site-packages/pyexcel/sources/__init__.pyc in get_sheet(**keywords)
    180         if field in keywords:
    181             sheet_params[field] = keywords.pop(field)
--> 182     named_content = _get_content(**keywords)
    183     sheet = Sheet(named_content.payload, named_content.name, **sheet_params)
    184     return sheet

/home/gf/.virtualenvs/me-app-env/local/lib/python2.7/site-packages/pyexcel/sources/__init__.pyc in _get_content(**keywords)
    137         sheet_name, data = source.get_data()
    138         return SheetStream(sheet_name, data)
--> 139     raise NotImplementedError(MESSAGE_ERROR_NO_HANDLER)
    140 
    141 

NotImplementedError: No suitable plugins imported or installed
`

**Comment by chfw** [comment]
please follow the documentation [here](http://pyexcel.readthedocs.org/en/latest/capability.html)

There is typo in your function call. filename should be file_name.

**Comment by germanferrero** [comment]
Ok, typo..
closing this !

**Comment by chfw** [comment]
no need to import pyexcel_io if you have imported pyexcel. here is [the architecture of pyexcel](http://pyexcel.readthedocs.org/en/latest/_images/architecture.png)

**Comment by chfw** [comment]
since pyexcel-io v0.2.0(pyexcel v0.2.2), pyexcel.ext.* is deprecated and all external pyexcel plugins are loaded automatically if it is installed.
