### ISSUE TITLE
To enable the user of pyexcel to control the default representation of pyexcel sheet and book

### ISSUE THREAD

**Issue by chfw** [pyexcel/pyexcel#31]
Continuing from https://github.com/pyexcel/pyexcel/issues/29

pyexcel-text modifies the default string presentation of pyexcel sheet, which is an additional functionality that other pyexcel plugins do not do. It does become a problem when the user of pyexcel does not want presentation modification but still needs pyexcel-text for text file writing. Let me think about the solution.

**Comment by Gryffoon** [comment]
Ok
