### ISSUE TITLE
Different displays between when opening the file and directly in v0.2.1

### ISSUE THREAD

**Issue by Gryffoon** [pyexcel/pyexcel#32]
I remarked something strange in this version 0.2.1.

When we put a number as an int, if we print the table, it displays the number as an int. 

But, if we save the file then reopenning it, displays it as a float. It is strange.

Look at the following code:

```
>>> import pyexcel as pe
>>> import pyexcel.ext.ods3
>>> a=[[60, 50.0, '120']]
>>> s=pyexcel.get_sheet(array=a)
>>> s
Sheet Name: pyexcel_sheet1
+----+------+-----+
| 60 | 50.0 | 120 |
+----+------+-----+
>>> s.save_as("sr.ods")
>>> o = pe.get_sheet(file_name="sr.ods")
>>> o
Sheet Name: pyexcel_sheet1
+------+------+-----+
| 60.0 | 50.0 | 120 |
+------+------+-----+
>>> 
```

Before saving into a file 60 is displayed as an int, and after saving into a file it is displayed as a float (60.0).

**Comment by Gryffoon** [comment]
In the version 0.2.0 this is what it gaves me: 

```
>>> import pyexcel as pe
>>> import pyexcel.ext.ods3
>>> a=[[60, 50.0, '120']]
>>> s=pyexcel.get_sheet(array=a)
>>> s
Sheet Name: pyexcel_sheet1
+----+----+-----+
| 60 | 50 | 120 |
+----+----+-----+
>>> s.save_as("sr.ods")
>>> o = pe.get_sheet(file_name="sr.ods")
>>> o
Sheet Name: pyexcel_sheet1
+----+----+-----+
| 60 | 50 | 120 |
+----+----+-----+
>>> 

```

Yes we don't see the issue since everything is printed as an int.

**Comment by chfw** [comment]
v0.2.0 works in the describe case because of the bug( #29) where column format(as text) wasn't enforced and texttable choose to display string in number on its own will (sometimes scientific way). Hence, v0.2.1 enforce that texttable to display all types as text .

 `int` is not in [the default numeric formats in ods](http://books.evc-cit.info/odbook/ch05.html#table-number-cells-section). So after saving the integer and read it back, you get a float type back instead of an integer one. 

I will look if I can detect an integer by this statement in the reference document:

    ..The value is stored without a decimal point if the value is an integer;..

**Comment by Gryffoon** [comment]
However when you read a table from an existing file and appending it with a new row, then print it. 

you have something like this

Row 1 :   45.0   30.0   32.0
Row 2 :   25      10      63

So you have an incoherent display, two kinds of displays at once.

**Comment by chfw** [comment]
> when you read a table from an existing file and appending it with a new row, then when you display it you have something like this :

    Row 1 :   45.0 |  30.0 | 32.0
    Row 2 :   25   | 10    | 63

If you want to get the integer types at run time, pyexcel.Sheet have [the facility to format them](http://pyexcel.readthedocs.org/en/v0.2.1/api.html#id4) ( (examples)[http://pyexcel.readthedocs.org/en/v0.2.1/tutorial03.html] )

**Comment by Gryffoon** [comment]
So I'll wait for the next release

**Comment by Gryffoon** [comment]
Here is the topic about integers and floats

**Comment by chfw** [comment]
Here's how to cope with it:

    >>> import pyexcel,pyexcel.ext.xls
    >>> a=[[1,1],[2.1,3.2]]
    >>> pyexcel.save_as(array=a, dest_file_name="test1.xls")
    >>> s=pyexcel.get_sheet(file_name="test1.xls")
    >>> s
    Sheet Name: pyexcel_sheet1
    +-----+-----+
    | 1.0 | 1.0 |
    +-----+-----+
    | 2.1 | 3.2 |
    +-----+-----+
    >>> s.to_array()
    [[1.0, 1.0], [2.1, 3.2]]
    >>> s.row.format(0, int)
    >>> s
    Sheet Name: pyexcel_sheet1
    +-----+-----+
    | 1   | 1   |
    +-----+-----+
    | 2.1 | 3.2 |
    +-----+-----+
    >>> s.to_array()
    [[1, 1], [2.1, 3.2]]

**Comment by chfw** [comment]
Reposted from #29:

Let me correct myself, with xlsx, you can save integer and get it back. for xls, you get float. csv, you get string. Here's what I have tried with(pyexcel=0.2.0 and other plugins were 0.1.x):

    >>> import pyexcel,pyexce.ext.xlsx
    >>> a=[[1,2],[1.1,2.2]]
    >>> pyexcel.save_as(array=a, dest_file_name="test.xlsx")
    >>> s=pyexcel.get_sheet(file_name="test.xlsx")
    >>> s.to_array()
    [[1, 2], [1.1, 2.2]]
    >>> import pyexcel.ext.xls
    >>> pyexcel.save_as(array=a, dest_file_name="test.xls")               
    >>> s2=pyexcel.get_sheet(file_name="test.xls")
    >>> s2.to_array()
    [[1.0, 2.0], [1.1, 2.2]]
    >>> pyexcel.save_as(array=a, dest_file_name="test.csv")
    >>> s3=pyexcel.get_sheet(file_name="test.csv")
    >>> s3.to_array()
    [[u'1', u'2'], [u'1.1', u'2.2']]

**Comment by Gryffoon** [comment]
"you can save integer and get it back. for xls, you get float. csv, you get string. Here's what I have tried with(pyexcel=0.2.0 and other plugins were 0.1.x)"

So you thnik there is a solution for this issue ?

**Comment by chfw** [comment]
What I tried to correct is: using pyexcel-xslx(openpyxl), you can save integer and get integers. 

The blocker is: xlrd library and csv format: saving integers into xls type via xlrd is [rejected by its maintainer](http://stackoverflow.com/a/8826770/2689383).

I am still thinking about the solution for it. Will update later

**Comment by Gryffoon** [comment]
I think this is a legitimate issue to fix for the xlrd developpers, and to add an issue to fix for them:

https://github.com/python-excel/xlrd/issues

For csv format, it is particular and all on it is a string, it is normal that you would not work. I don't know if there is a solution for csv files, but it might be risky.

**Comment by Gryffoon** [comment]
I understood that in Excel all number data is displayed as a float. However as you said we can choose to have a new cell formatting (by default) which give something ilke that:

If the number is mathematically an integer  ( float(x) - float(int(x)) == 0.0 ) so display it as an int. 
Else the number is mathematically a decimal so display it as a float. 

Or otherwise if the user don't this type of display he can use the cell formatting.

**Comment by chfw** [comment]
Yes, that's what I am doing, adding the data mangling layer in pyexcel-xls, pyexcle-ods(3).  For people who do not want this, they could switch it off by supplying 'auto_detect_int=False' in get_sheet() keywords.

I am considering doing the same for csv files.

**Comment by Gryffoon** [comment]
I suggest another solution, and it is to have something like this:

MyWorkbook['MySheet'].format("auto")

MyWorkbook['MySheet'].format(int)

MyWorkbook['MySheet'].format(float)

MyWorkbook['MySheet'].format("auto")

This way you can switch between formatting. 


I don't know what this way "'auto_detect_int=False' in get_sheet() " will give, it can enter in conflict with sheet formatting. Be careful. 

Example: 

Somebody want to open it with int detection:

he will do 'auto_detect_int=True' in get_sheet()
then for some reason he want to format the whole sheet as a float. 
MyWorkbook['MySheet'].format(float)

Then for some reason he want to return to int autodetection
and he can't do MyWorkbook['MySheet'].format(auto)

So I suggest to have a new kind of formatting (auto) instead of having an option in get sheet.

**Comment by Gryffoon** [comment]
In excel/ods software there is an also automatic detection as a format and is named "Standard", it is not really the same but its the same, but it's the same philosophy:

(My Excel is in French)

![2016-04-27_124057](https://cloud.githubusercontent.com/assets/15887222/14849805/6e179f6c-0c75-11e6-86fc-726f1c586345.png)

**Comment by chfw** [comment]
will provide an example 'auto_detect_int' of get_sheet(get_book) later. 

.format('auto') looks good for array of texts, the things that usually come out from a csv file.

**Comment by chfw** [comment]
sheet.format('auto') could be applied in this situation:

    array = [["1", "2.1", "2016-05-04"]]
    sheet = pyexcel.Sheet(array)
    sheet.format("auto")

It could be considered in next code refactoring round.

With the on-going changes to pyexcel plugins, I think those changes would normalize the data types coming into pyexcel. After the changes are released, other users like you would not see any difference in display and data types, regardless of the file format.

**Comment by chfw** [comment]
Here is [some example on the flags](http://pyexcel-io.readthedocs.io/en/latest/plaincsv.html#read-from-a-csv-file)

**Comment by Gryffoon** [comment]
good to hear

**Comment by chfw** [comment]
all required changes have been made. pending for documentation and then release.

**Comment by chfw** [comment]
all have been released
