### ISSUE TITLE
Enhancement suggestion: The table could be displayed without sheet name

### ISSUE THREAD

**Issue by Gryffoon** [pyexcel/pyexcel#35]
Hi, 

The pyexcel display module is aboslutely sublime and useful not only for manipulating excel/ods/csv workbooks, but also to display a result in the console. However, the fact that we have sheet name keyword and its name every time near the table that we have to display is sometimes annoying, when we don't need it. 

So I suggest to have an option or a new functionality, so that instead of having this (*)
![2016-04-27_101732](https://cloud.githubusercontent.com/assets/15887222/14846150/813d5c70-0c62-11e6-8044-b0b2f2bbb135.png)

We'll have this
![2016-04-27_101733](https://cloud.githubusercontent.com/assets/15887222/14846194/c46b574a-0c62-11e6-9d53-ba3a795594a1.png)

And possibily an option or functionality to get this kind of display (instead of (*)):

![2016-04-27_101732](https://cloud.githubusercontent.com/assets/15887222/14846375/c51b5180-0c63-11e6-9121-554205a793c7.png)

**Comment by chfw** [comment]
Could remove 'Sheet Name' from it. To print sheet without name, it is better to be provided an alternative function call. The last print of Sheet looks neat.

**Comment by Gryffoon** [comment]
Yes we can have alternative function call

**Comment by Gryffoon** [comment]
We can also need to have this

![813d5c70-0c62-11e6-8044-b0b2f2bbb5](https://cloud.githubusercontent.com/assets/15887222/14880743/d9d920f2-0d30-11e6-91f0-7ce834ad5460.png)

So I have an idea:

we can do 

```
>>> sh = get_sheet(...)
>>> sh_name = get_sheetname(sh)
>>> print(sh_name)
'Sheet 1'
```

then print(sh) will give
`>>> print(sh)`
![813d5c70-0c62-11e6-8044-b0b2d35](https://cloud.githubusercontent.com/assets/15887222/14880920/e8e80dc8-0d31-11e6-8af6-e7ae770eeed8.png)

and an alternative function printgrid() will give

`>>> printgrid(sh)`
![813d5c70-0c62-11e6-8044-b0b2f2bbb5](https://cloud.githubusercontent.com/assets/15887222/14881318/bd12ab16-0d33-11e6-9030-bc27ea9d3839.png)

If we want the sheet name, we can do:
```
print(sheetname + ":")
printgrid(sh)
```
So finally we'll have: 
![813d5c70-0c62-11e6-8044-b0b2f2bbb5](https://cloud.githubusercontent.com/assets/15887222/14881327/c40c2b2c-0d33-11e6-9eb3-7ae1be1124df.png)

**Comment by Gryffoon** [comment]
So what do you think ? About this solution ?

**Comment by chfw** [comment]
what about this?

    >>> sheet
    Your sheet name:
    +----+------+-----+
    | 60 | 50.0 | 120 |
    +----+------+-----+
    >>> sheet.content
    +----+------+-----+
    | 60 | 50.0 | 120 |
    +----+------+-----+

**Comment by Gryffoon** [comment]
That sounds good
