### ISSUE TITLE
About the webdocumentation

### ISSUE THREAD

**Issue by Gryffoon** [pyexcel/pyexcel#36]
Hi, 

There is two webdocumentation for pyexcel 

1) https://pyexcel.readthedocs.org/en/latest/design.html

&

2) http://pythonhosted.org/pyexcel/index.html

My favorite is the (1), however, what I see is that both of them are uncompleted. And some times we need to witch from one to the other to get the whole information we need to code.

**Comment by chfw** [comment]
will enhance it.

**Comment by chfw** [comment]
option 1) and 2) were enhanced.

**Comment by Gryffoon** [comment]
there is still some empty paragraphs like this one:

http://pyexcel.readthedocs.io/en/latest/tutorial04.html#merge-excel-books

> 
> Merge excel books
> Suppose you have two excel books and each had three sheets. You can merge them and get a new book:
> 
> .. testcode::
> hide:

**Comment by Gryffoon** [comment]
However, all the rest sounds good with the new signature functions etc...

**Comment by Gryffoon** [comment]
There is maybe an error here

![2016-04-28_122919](https://cloud.githubusercontent.com/assets/15887222/14883202/24cfc1b8-0d3d-11e6-8b02-e6ed923b34ae.png)

**Comment by chfw** [comment]
Enhanced again. You are the eyes of the users. Thanks.

**Comment by Gryffoon** [comment]
No problem
