### ISSUE TITLE
pypy3 test fails

### ISSUE THREAD

**Issue by chfw** [pyexcel/pyexcel#37]
it's been noticed that [nosetests cannot run under pypy3](https://travis-ci.org/pyexcel/pyexcel/jobs/126440817). however, pyexcel-text, pyexcel-xlsx, pyexcel-xls are tested OK in pypy3.

**Comment by jayvdb** [comment]
Just noting, nose passes its own tests on pypy3
https://travis-ci.org/jayvdb/nose/builds/126686327

I'll dig a bit further...

**Comment by chfw** [comment]
nosetests for pyexcel-text, pyexcel-xlsx, pyexcel-xls, pyexcel-io under pypy3 are passing too.

**Comment by jayvdb** [comment]
ok, then I wont bother too much.

I disabled coverage and doctest and nose is still core dumping on each and every test module.

I've done a PR for PyPy3 for nose ( https://github.com/nose-devs/nose/pull/995 ) . Will see how that goes; the number of old simple open PRs is a worry.

**Comment by jayvdb** [comment]
I encountered a very similar looking seg fault on `pypy`.

https://travis-ci.org/jayvdb/pyexcel/jobs/126806718

it disappeared on my next build.
