### ISSUE TITLE
texttable-0.8.1

### ISSUE THREAD

**Issue by jayvdb** [pyexcel/pyexcel#38]
Currently the minimum version of texttable is >=0.8.2 , but I cant find a bug in 0.8.1.

See two commits in https://github.com/jayvdb/pyexcel/commits/texttable-0.8.1 , and successful build at https://travis-ci.org/jayvdb/pyexcel/builds/126812754 .

If there are serious bugs in 0.8.1, we should add a test that fails on 0.8.1.

Debian sid and ubuntu trusty-yakkety all provide 0.8.1 as OS packages, so it would be good if we could use 0.8.1, or request that debian/ubuntu bump their version if there is a serious bug.

https://packages.debian.org/search?suite=sid&searchon=names&keywords=python-texttable
http://packages.ubuntu.com/trusty/python-texttable
http://packages.ubuntu.com/yakkety/python-texttable

**Comment by chfw** [comment]
I just digged up [the reason for dropping 0.8.1](https://github.com/bufordtaylor/python-texttable/issues/13): v0.8.1 back then does not support python 3 while v0.8.2 supports both py2 and py3.

**Comment by jayvdb** [comment]
Ah, that makes sense.  So we can support v0.8.1+ on Python 2, and v0.8.2+ on Python 3 ...?
If so, I'll tidy up much patch and submit a PR

**Comment by chfw** [comment]
Yep, we can do that.

**Comment by jayvdb** [comment]
Just noting, as it will be relevant to my future patches, that https://pypi.python.org/simple/texttable/ only contains 0.8.3 and 0.8.4, and I have had no response for over a week on https://github.com/foutaise/texttable/issues/5 , so 0.8.2 cant easily be installed & tested.
No doubt the internets has old copies online that can be used, but it does complicate matters as we cant just tell pip "texttable=0.8.2" and let it grab it.
