### ISSUE TITLE
tests fail on master

### ISSUE THREAD

**Issue by jayvdb** [pyexcel/pyexcel#40]
There are now [25 tests failing](https://travis-ci.org/jayvdb/pyexcel/builds/128598366) on master, using the same commit (b6fd56e) as [previously passed](https://travis-ci.org/pyexcel/pyexcel/builds/127351718).

I'm not sure what the cause is, as the new builds have the same frozen list as the old list; which is also identical on py27 and py33: 

```
codecov==2.0.3
cov-core==1.15.0
coverage==4.0.3
ezodf==0.3.2
Flask==0.10.1
future==0.15.2
glob2==0.4.1
itsdangerous==0.24
jdcal==1.2
Jinja2==2.8
lxml==3.6.0
MarkupSafe==0.23
mock==1.0.1
nose==1.3.4
nose-cov==1.6
numpy==1.9.1
openpyxl==2.2.2
py==1.4.26
pyexcel==0.2.1
pyexcel-io==0.2.0
pyexcel-ods3==0.2.0
pyexcel-text==0.2.0
pyexcel-xls==0.2.0
pyexcel-xlsx==0.2.0
pytest==2.6.4
requests==2.10.0
SQLAlchemy==1.0.12
tabulate==0.7.5
texttable==0.8.4
Werkzeug==0.11.9
wheel==0.24.0
xlrd==0.9.4
xlwt-future==0.8.0
```

The "Build system information" details looks the same, including LANG variables, etc.

**Comment by chfw** [comment]
Will have a look later.
