### ISSUE TITLE
error in pyexcel setup command: Invalid environment marker: platform_python_implementation=="PyPy"

### ISSUE THREAD

**Issue by chfw** [pyexcel/pyexcel#49]
Since pyexcel v0.2.2, the user of pyexcel would have this problem if you have old setuptools installed:

    error in pyexcel setup command: Invalid environment marker: platform_python_implementation=="PyPy"

You will need to do:

    pip install --upgrade setuptools

Let's document this in the doc as well.

**Comment by edouardberthe** [comment]
👍 Thank you

**Comment by Vankash** [comment]
Thanks a bunch!

**Comment by chfw** [comment]
Since version 0.2.5, the requirement on setuptools has been downgraded. In other words, this problem won't appear for pyexcel users. However, setuptools upgrade is still complusory for the contributors of pyexcel .

**Comment by hansyiu** [comment]
Very helpful！
