### ISSUE TITLE
Issue installing from pip on Windows with 0.2.2

### ISSUE THREAD

**Issue by jonathanrocher** [pyexcel/pyexcel#52]
If this is not the right place to report this issue, let me know the right place. I am seeing issues installing the newest version of `pyexcel` on Windows 64bit and on OSX 64bit:
```
Collecting pyexcel
  Using cached pyexcel-0.2.2.zip
    Complete output from command python setup.py egg_info:
    error in pyexcel setup command: Invalid environment marker: platform_python_implementation=="PyPy"
```

I am not seeing this issue with 0.2.1 so my workaround is to stay on the previous version:
```
pip install pyexcel==0.2.1
```

**Comment by jonathanrocher** [comment]
Sorry, I realize that you have posted a comment about his in your docs:
https://pyexcel.readthedocs.io/en/latest/migration_guide.html#invalid-environment-marker-platform-python-implementation-pypy
Closing, sorry for the noise...

**Comment by chfw** [comment]
Thanks for using pyexcel v0.2.2, which took me a while to deliver.

**Comment by chfw** [comment]
Since version 0.2.5, the requirement on setuptools has been downgraded. In other words, this problem won't appear for pyexcel users. However, setuptools upgrade is still complusory for the contributors of pyexcel .
