### ISSUE TITLE
To  support hidden columns

### ISSUE THREAD

**Issue by chfw** [pyexcel/pyexcel#53]
Let's investigate the feasibility first.

reference: https://github.com/pyexcel/pyexcel/issues/21

**Comment by gamesbook** [comment]
Any progress on this in the last year?  Thanks!

**Comment by chfw** [comment]
Thanks for your interest in this enhancement. To be honest, not much progress in this aspect yet. Will start looking at this after pyexcel v0.5.0 is released.

**Comment by gamesbook** [comment]
OK, thanks. I will tell the users not to expect this option any time soon...

**Comment by chfw** [comment]
xlrd(xls, xlsx) supports hidden column: https://github.com/python-excel/xlrd/blob/fcfdb721abe650c0b25d8a874dc7314e9eb8dc59/xlrd/sheet.py#L2354

**Comment by chfw** [comment]
openpyxl seems to have column_dimensions to tell if a column is hidden or not. https://stackoverflow.com/questions/31257353/finding-hidden-cells-using-openpyxl

**Comment by gamesbook** [comment]
Not sure how this is relevant to the pyexcel project?

**Comment by chfw** [comment]
Pyexcel is a wrapper library and uses them to access the excel files. So if the underlying libraries have the support, pyexcel should be able to support hidden column. I will need to look at odfpy and ezodf still.

**Comment by chfw** [comment]
I am not able to get any support for odfpy and ezodf. I am afraid that ods format will not have this feature. So, I am going to close this long standing feature request as pyexcel-xls and pyexcel-xlsx will have this feature delivered soon.

**Comment by gamesbook** [comment]
@chfw Is there an open issue specifically for pyexcel-xls and pyexcel-xlsx ?

**Comment by chfw** [comment]
Please see the linked issues.

**Comment by chfw** [comment]
please try the released plugins: pyexcel-xls for xls file, pyexcel-xlsx for xlsx file. by default, rows and columns will be skipped.

**Comment by gamesbook** [comment]
What is meant by "skipped"?  A hidden row/col is still in the sheet; just not visible.

**Comment by chfw** [comment]
'skipped' means: pyexcel won't read them out although they exist in the sheet. Change skip_hidden_row_and_column=False, you will read them out. These read operations won't change the excel file.

**Comment by gamesbook** [comment]
Thanks; and I assume hidden rows/cols can be created?

**Comment by chfw** [comment]
No. Will need to schedule the feature separately. I have a plan to write some styles out across the file formats, column width will be in and can roll this hidden rows and columns into it. Let me create an issue to track it.

**Comment by xuanphu026** [comment]
You can help me open file .xlsm using closedxml by c#. Thank you!
