### ISSUE TITLE
Changes Date Format Incorrectly

### ISSUE THREAD

**Issue by Rehgan** [pyexcel/pyexcel#54]
from pyexcel.ext import xls
from pyexcel.ext import xlsx

pyexcel.get_book(file_name='Data Issue.xls').save_as(folderpath + "CSV Input Files\\" + "Processing_" + newFileName + ".csv")

This is a bit of the code I use to convert a bunch of excel files of various formats to csvs. The attached file is the xls file that I try to convert and contains a column with dates in a date format. The date is 06/12/16 and this library changes it to 06/11/2012 for some reason.

Github won't allow me to upload a .xls so I have attached the xlsx file. To replicate the issue, save the file as a .xls. The problem will still occur.
[Date Issue.xlsx](https://github.com/pyexcel/pyexcel/files/374457/Date.Issue.xlsx)

Any idea why this could be happening? Potentially it is that I import the xlsx after the xls library.

**Comment by chfw** [comment]
Hey, I am not able to reproduce it with the following setup:

    pyexcel==0.2.4
    pyexcel-io==0.2.1
    pyexcel-xls==0.2.0
    pyexcel-xlsx==0.2.0

And with pyexcel >= 0.2.2, you need to pay attention to [this migration note](http://pyexcel.readthedocs.io/en/latest/migration_guide.html#how-to-keep-both-pyexcel-xls-and-pyexcel-xlsx). Here is an example:

    >>> import pyexcel
    >>> pyexcel.get_book(file_name="Date.Issue.xls", library="pyexcel-xls")

**Comment by chfw** [comment]
please re-open it if the problem is still there

**Comment by chfw** [comment]
pip install pyexcel-xls==0.5.7 should fix the problem for you. Meanwhile, I am seeking to fix pyexcel-xlsx.

I am sorry to have been so slow to recognise it as a bug.
