### ISSUE TITLE
Import error pyexcel_chart

### ISSUE THREAD

**Issue by nmtbk** [pyexcel/pyexcel#62]
I got this exception, pyexcel installed via pip. Thanks.

Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

> > > import pyexcel
> > > Failed to import pyexcel_chart due to %s
> > > Traceback (most recent call last):
> > >   File "C:\Users\myuser\Envs\myvirtualenv\lib\site-packages\pyexcel\renderers__init__.py", line 19, in <module>
> > >     import pyexcel_chart
> > > ImportError: No module named 'pyexcel_chart'

**Comment by chfw** [comment]
made a follow-up release. thanks for your report.

**Comment by nmtbk** [comment]
Thank you, i've tested by the your sample code on Debian and python 2.7, not get above exception but other messages come:
>>> import pyexcel as pe
No handlers could be found for logger "pyexcel.renderers"
>>> records = pe.iget_records(file_name="your_file.xls")
>>> for record in records:
...     print("%s is aged at %d" % (record['Name'], record['Age']))

/usr/local/lib/python2.7/dist-packages/openpyxl-2.4.0-py2.7.egg/openpyxl/worksheet/worksheet.py:300: UserWarning: Using a coordinate with ws.cell is deprecated. Use ws[coordinate] instead
  warn("Using a coordinate with ws.cell is deprecated. Use ws[coordinate] instead")

**Comment by chfw** [comment]
Those are warnings which won't affect its software quality. Please continue using it while I will remove those user warnings.

**Comment by chfw** [comment]
Do you mind trying it again? But this time, can you try the master branch first? Just case other things come up again.

    https://github.com/pyexcel/pyexcel/archive/master.zip
    https://github.com/pyexcel/pyexcel-xlsx/archive/master.zip

**Comment by nmtbk** [comment]
Download above links and have tested again on Debian and python 2.7, clean and run smoothly. Thank you very much.

Have nice weekend!

**Comment by chfw** [comment]
both packages were released

**Comment by chfw** [comment]
v0.5.0 will fix this issue eventually.
