### ISSUE TITLE
pyexcel-ods has become incredibly slow

### ISSUE THREAD

**Issue by Gabriel-p** [pyexcel/pyexcel#65]
I'm trying to read an .ods file (~360 kb, attached). It used to take a few seconds before (it wasn't immediate), but now it takes almost 6 min in the same machine (!).

I'm using pyexcel-ods v0.2.2.

[lit_OCs_data.ods.zip](https://github.com/pyexcel/pyexcel/files/627665/lit_OCs_data.ods.zip)

**Comment by chfw** [comment]
reproduced with v0.2.2 and it was OK with 0.2.0. Will look into it.

**Comment by chfw** [comment]
To evaluate it, unfortunately you will need to install un-released pyexcel and pyexcel-io:

    pip install https://github.com/pyexcel/pyexcel/archive/io3.zip
    pip install https://github.com/pyexcel/pyexcel-io/archive/master.zip
    pip install https://github.com/pyexcel/pyexcel-ods/archive/master.zip

**Comment by Gabriel-p** [comment]
Indeed, it is *much* faster now.

Will the package update itself eventually (now that I've installed the patched version using your instructions above), or should I remove it and install the current PypI version?

**Comment by chfw** [comment]
The patched version is not released yet. My suggestion is to use pyexcel-ods v0.2.0 till the patched version will be released.

**Comment by chfw** [comment]
released to pypi with pyexcel-ods v0.3.0
