### ISSUE TITLE
save_to_memory function

### ISSUE THREAD

**Issue by shanyj** [pyexcel/pyexcel#68]
hi~
  I notice that in pyexcel==0.2.5, save_to_memory function in pyexcel.book.py and pyexcel.sheets.sheet return a StringIo type, However in pyexcel==0.4.0, it returns a str type which make seek() func in my project throw a error.
  I am curious about why use str instead of StringIo type?~

Regards
Yj

**Comment by chfw** [comment]
I am sorry for this surprise. Its implementation was changed without actual specific requirements. I would take this as a regression and restore its functionality. Stay tuned.

**Comment by chfw** [comment]
Please have a go on it before I release it to pypi .

**Comment by shanyj** [comment]
thx~

**Comment by chfw** [comment]
It was found that the stream should have been sought at 0 before returning. 

reference: https://github.com/pyexcel/django-excel/issues/33
