### ISSUE TITLE
ImportError: cannot import name 'RWManager'

### ISSUE THREAD

**Issue by FpereraMaia** [pyexcel/pyexcel#72]
I used the version: 

Flask-Excel==0.0.5
pyexcel-xlsx==0.3.0

And in "site-packages/pyexcel/renderes/_excel.py", at line 2 have:
"from pyexcel_io import save_data, RWManager"

but "RWManager" not found. What could it be?

Thanks.

**Comment by chfw** [comment]
You will need pyexcel v 0.4.0+ and pyexcel-io v0.3.0+

**Comment by FpereraMaia** [comment]
Thanks man.
