### ISSUE TITLE
XLSB support?

### ISSUE THREAD

**Issue by rickyoshi** [pyexcel/pyexcel#73]
I see XLS and XLSX and ODS but I do not see XLSB?

**Comment by chfw** [comment]
I am afraid that no library is available in python world:

https://bitbucket.org/openpyxl/openpyxl/issues/249/read-and-write-xlsb-files
https://github.com/python-excel/xlrd/issues/83

Here is some suggestions:

http://stackoverflow.com/questions/22366200/how-can-i-convert-a-xlsb-file-to-csv-using-python

**Comment by chfw** [comment]
there may be a possibility to read xlsb file. 

https://github.com/wwwiiilll/pyxlsb

**Comment by chfw** [comment]
please watch this repo: https://github.com/pyexcel/pyexcel-xlsbr in development.

**Comment by chfw** [comment]
pyexcel-xlsbr v0.0.1 is released
