### ISSUE TITLE
No documitaiton how to read a csv with a custom delimiter

### ISSUE THREAD

**Issue by guysoft** [pyexcel/pyexcel#75]
Hey,
I want to read a csv that has tab as its delimiter. 
I can't find anything in the documentation or code on how to force that.
Can you please explain what is missing to implement this/give a usage example?

Thanks,

**Comment by chfw** [comment]
please find [it](http://pyexcel.readthedocs.io/en/latest/tutorial_data_conversion.html#how-to-save-an-python-array-as-a-csv-file-with-special-delimiter) here. I will organise it later.

**Comment by guysoft** [comment]
Thats reading,  not saving.

**Comment by chfw** [comment]
My bad. Here is a read example:

    >>> import pyexcel as p
    >>> s=p.get_sheet(file_name='test.csv', delimiter='\t')
    >>> s
    test.csv:
    +---+---+---+
    | 1 | 2 | 3 |
    +---+---+---+
    | 4 | 5 | 6 |
    +---+---+---+
    >>> exit()
    $ cat test.csv
    1       2       3
    4       5       6

**Comment by guysoft** [comment]
Thanks!

**Comment by chfw** [comment]
> “To err is human, to forgive, divine.”
> 
> 
> ― Alexander Pope, An Essay on Criticism
