### ISSUE TITLE
pyexcel_chart module not in PyPi

### ISSUE THREAD

**Issue by raulk** [pyexcel/pyexcel#80]
The package init of pyexcel.renderers complains if it cannot find the pyexcel_chart module, but it is not published on PyPi.

**Comment by chfw** [comment]
Did you spot it in your log output?

It is reported here: https://github.com/pyexcel/pyexcel/issues/62 but it was kept as info log in v4.4. And [this behaviour is corrected in v0.5.0](https://github.com/pyexcel/pyexcel/commit/9efb04216016fe66950de9c793d654f7bca7cb8f).

**Comment by raulk** [comment]
@chfw yes, it's in the log output. But 0.5.0 has not been released, right? At least it is not published on PyPi.

**Comment by chfw** [comment]
v0.5.0 will take some time to come out. I will make patch for v0.4.x branch to address it then.

**Comment by chfw** [comment]
the fix is released to pypi, dropping pyexcel-chart import
