### ISSUE TITLE
Parsing ODS file: Missing text when there are double/multiple whitespaces in cell

### ISSUE THREAD

**Issue by hieu-n** [pyexcel/pyexcel#81]
Package version:

> Flask-Excel (0.0.5)
> pyexcel (0.4.5)
> pyexcel-io (0.3.3)
> pyexcel-ods (0.3.2)
> pyexcel-webio (0.0.11)
> pyexcel-xls (0.3.1)

I'm using `flask-excel`/`pyexcel` to parse ODS files sent by my users. Recently, I have encountered an ODS file that got parsed improperly by `pyexcel`.  The basic structure of the file is as below:

| id              | name           | 
| --- | --- |
| PRODUCT_ID | PRODUCT NAME  PMP |

The file is attached:
[Product1.ods.zip](https://github.com/pyexcel/pyexcel/files/972829/Product1.ods.zip)

There are double white spaces in between `PRODUCT NAME` and `PMP`. The `pyexcel`'s `get_records` returns only `PMP` for value in the `name` column instead of `PRODUCT NAME  PMP`. 

Note: Github automatically removes double white spaces when I tried to type double white spaces.

**Comment by chfw** [comment]
for future reference, here is the actual xml that both library failed to extract text from:

> <table:table-cell table:style-name="ce1" office:value-type="string" calcext:value-type="string><text:p>PRODUCT NAME <text:s/>PMP</text:p></table:table-cell>

**Comment by chfw** [comment]
released to pypi.
