### ISSUE TITLE
pyinstaller packaging: pyexcel.exceptions.UnknownParameters file_name

### ISSUE THREAD

**Issue by georgesimeo** [pyexcel/pyexcel#88]
I run Python 3.5.3 (64 bit) on Windows 7 after making exe with pyinstaller 
My script stops working (file and path are checked to be correct), but I got that exception. 
pyexcel.exceptions.UnknownParameters: Please check if there were typos in function parameters: {'file_name': 'C:\\py\\input_data.xls'}. Otherwise unrecognized parameters were given.

Here is function call 
filename = r'C:\py\input_data.xls'
if os.path.exists(filename):
	sheet = pyexcel.get_sheet(file_name=filename)

**Comment by chfw** [comment]
This must have something to do with hidden imports. Which versions of pyexcel and pyexcel-io are you   using?

**Comment by georgesimeo** [comment]
I used pip to install pyexcel 
pip list
pip (9.0.1)
pyexcel (0.5.0)
pyexcel-io (0.4.0)
pyexcel-xls (0.4.0)
future (0.16.0)
lml (0.0.1)
PyInstaller (3.2.1)
pypiwin32 (219)
setuptools (28.8.0)
texttable (0.9.0)
xlrd (1.0.0)
xlwt (1.2.0)

**Comment by chfw** [comment]
Just an update: reproduced over here.

**Comment by chfw** [comment]
The full command line options are:

    C:\>pyinstaller m.py --hidden-import pyexcel.plugins.sources.file_input --hidden-import pyexcel.plugins.parsers.excel --hidden-import pyexcel_xls --hidden-import pyexcel_xls.xlsr

with pyexcel v0.5.0 and pyexcel 0.4.0, pyinstaller options become long. The reason is that all plugins were loaded on demand. It means, in your case, only the components mentioned in the hidden imports were imported by Python into memory. When you packaging your application up, pyinstaller could not capture this dynamic behavior.  

Here is [instructions on pyexcel-io](http://pyexcel-io.readthedocs.io/en/latest/pyinstaller.html). I am yet document pyexcel in this regard later.

**Comment by georgesimeo** [comment]
Thank you a lot!
I tried and looks to be solved exception from
/// sheet = pyexcel.get_sheet(file_name=filename)
But I have another exception for csv from 
///  sheet.save_as('temp_input.csv')

I have added hidden imports  pyexcel_io.writers.csvw / pyexcel_io.readers.csvr.
I'm still getting this: 
"pyexcel.exceptions.FileTypeNotSupported: File type 'csv' is not supported for write."

pyinstaller --noconfirm --log-level=DEBUG ^
    --onefile ^
    --hidden-import pyexcel.plugins.sources.file_input ^
    --hidden-import pyexcel.plugins.parsers.excel ^
    --hidden-import=pyexcel_io.readers.csvr ^
    --hidden-import=pyexcel_io.readers.csvz ^
    --hidden-import=pyexcel_io.writers.csvw ^
    --hidden-import=pyexcel_io.readers.csvz ^
    --hidden-import=pyexcel_xlsxw ^
    --hidden-import=pyexcel_xlsxw.xlsxw ^
    --hidden-import=pyexcel_xls ^
    --hidden-import=pyexcel_xls.xlsr ^
    --hidden-import=pyexcel_xls.xlsw ^
    myscript.spec

**Comment by chfw** [comment]
--hidden-import=pyexcel_io.readers.csvr  should be enough but I am not sure about '=' sign there.

**Comment by georgesimeo** [comment]
Exception about 'csv' remains even after removing all '='.  I tried both via command line and with bat file.
No errors from pyinstaller.

**Comment by chfw** [comment]
Oh, my bad. It should be

    --hidden-import pyexcel_io.writers.csvw

because you read from xls and write it to csv.

**Comment by georgesimeo** [comment]
It is also imported and I'm still getting csv exception
--hidden-import pyexcel_io.writers.csvw

**Comment by georgesimeo** [comment]
Bad I tried to write my own export to csv 

        with open('temp_input.csv','w',newline='',encoding='utf8') as csvfile:
            writer = csv.writer(csvfile)
            for r in range(len(sheet.array)):
                writer.writerow(sheet.array[r])
            csvfile.close()

And ... no luck after pyinstaller 

I got this when tried to run compiled exe

  File "site-packages\pyexcel\internal\meta.py", line 30, in custom_presenter
  File "site-packages\pyexcel\internal\source_plugin.py", line 91, in get_writable_source
  File "site-packages\pyexcel\internal\source_plugin.py", line 65, in get_a_plugin
  File "site-packages\pyexcel\internal\source_plugin.py", line 40, in load_me_now
  File "site-packages\lml\plugin.py", line 303, in dynamic_load_library
  File "site-packages\lml\utils.py", line 59, in do_import_class
ImportError: No module named 'pyexcel.plugins.sources.pydata'

**Comment by chfw** [comment]
Here's [pyinstaller documentation](http://pyexcel.readthedocs.io/en/latest/pyinstaller.html) regarding pyexcel

**Comment by chfw** [comment]
I am sorry for endless list of hidden imports. Any updates on your side? Did your script work in the end?

**Comment by chfw** [comment]
No response. Please re-open if the issue rise again.
