### ISSUE TITLE
Unable to add new line to excel dataframe 

### ISSUE THREAD

**Issue by geeek987** [pyexcel/pyexcel#91]
I wanted to print excel output like this. (I have  50 other columns like N and A) This is just a sample.. 
        N                     A
N1 | N2 | N3 | | A1 | A2 | A3
10 | 22 | 12   | | d    | h   | f
18 | 24 | 33   | | j     | o   | g
13 | 23 | 25   | | g    | k   | h
20 | 23 | 18   | | h    | d   | g

My code looks like
----------------------------------------------------------------------------------------
`
    ```
     sheet = pe.get_sheet(file_name="Mylist.xlsx")
      for _ in range(5):
      y=(random.sample(range(30), 3))
      sheet.row +=[y]
      sheet.save_as("Mylist.xlsx")
    
    for _ in range( 3 ):

    letters = [i for i in string.ascii_lowercase]
    random_list = random.sample( letters, 3 )
    x=random_list
   
    sheet.row +=[x]
    sheet.save_as("Mylist.xlsx")

`
---------------------------------------------------------------------------------
By referring to the documentation I used the new line feature. However, this is how I am getting my output. 

N1| N2 | N3

10 | 22 | 12
18 | 24 | 33
13 | 23 | 25
20 | 23 | 18
0 | 10 | 23
10 | 3 | 15
26 | 10 | 9
n | q | w
e | h | m
q | l | f

Is there a solution to this in Pyexcel? Thank you!

**Comment by chfw** [comment]
Let me understand the problem first. I read that you want place some columns on the right hand side of N1|N2|N3. Where is your A1|A2|A3? Do you have trouble in inserting 'N A'?

**Comment by geeek987** [comment]
![data](https://user-images.githubusercontent.com/30086914/28126662-1dcd081a-66f8-11e7-8a00-bb60de4e89a6.PNG)
![ot](https://user-images.githubusercontent.com/30086914/28126661-1dc89546-66f8-11e7-8ee7-6fac05d63d7e.PNG)

Hi, Here are the images. I am trying to save output of numbers in numbers(N) column and of alphabets in alphabet(A) column but when I add new line(containing alphabet list) as per the documentation, it gets added to the numbers column only. It doesn't save anything in alphabet column. And I have many other columns like (Numbers(N), Alphabets(A),Symbols(S), Alphanumeric(AL)....)  Hopefully you understood what I meant!

**Comment by chfw** [comment]
OK. If I understood correctly, you would like to have n,q,w right below h,d,g. 

With that understanding, you will need to make each new row as:

    row = [0, 10, 23, 'your date', 'n', 'q', 'w']
    sheet.row += row
    row = [10, 3, 15, 'another date', 'e', 'h', 'w']
    sheet.row += row
    ...

Above code illustrates how you could do it but it is not the shortest code.

**Comment by geeek987** [comment]
Yes! But I am generating n,q,w randomly and will not know what value is next. In that case how can I hard code n,q,w?

**Comment by chfw** [comment]
No need. you could do this:

    sheet.row += y + ['your date'] + x

**Comment by geeek987** [comment]
Hi, I am sorry !I am newbie. I think I could not explain my problem properly. I am getting output as y only. I don't have x. I have to partition the output of 'y' into different blocks as shown above. Here is how I am getting my output
I have an input  list: inputlist= [Numbers, Alphabets,Alphanumeric,.....]
My real program is really long. In a loop, it takes each element from the list performs some operation and finally produces an output and piles it up in y as follows: 
List Output
y= [Date ,0 , 10 , 23]
     [Date, 10 , 3 , 15]
     [Date, 26 , 10 , 9]
     [Date, n,  q , w]
     [Date, e ,  h , m]
     [Date, q ,  l  , f ]

And now this I want to separate as follows:
![capture](https://user-images.githubusercontent.com/30086914/28171604-f2879d04-67b6-11e7-8849-99c6d74c8611.PNG)
   
Sorry once again. Appreciate your help!
Thanks!

**Comment by geeek987** [comment]
Hi, I am sorry !I am newbie. I think I could not explain my problem properly. I am getting output as y only. I don't have x. I have to partition the output of 'y' into different blocks as shown above. Here is how I am getting my output
I have an input list: inputlist= [Numbers, Alphabets,Alphanumeric,.....]
My real program is really long. In a loop, it takes each element from the list performs some operation and finally produces an output and piles it up in y as follows:
List Output
y= [Date ,0 , 10 , 23]
[Date, 10 , 3 , 15]
[Date, 26 , 10 , 9]
[Date, n, q , w]
[Date, e , h , m]
[Date, q , l , f ]
And now this I want to separate as follows:
 
![capture](https://user-images.githubusercontent.com/30086914/28173828-9e67dc8c-67bd-11e7-859d-16df462a2c01.PNG)

 I know sheet.row += y+y will work but it is going serially 
![capture3](https://user-images.githubusercontent.com/30086914/28173972-21142320-67be-11e7-89ee-44393f874836.PNG)

Sorry once again. Appreciate your help!
Thanks!

**Comment by chfw** [comment]
You can populate left hand side with numbers, say left_sheet

![left-sheet](https://user-images.githubusercontent.com/4280312/28177782-db0ddf20-67f3-11e7-9113-65b298e73755.png)

Then populate right hand side with alphabets, say right_sheet

![right-sheet](https://user-images.githubusercontent.com/4280312/28177794-e7ff17d0-67f3-11e7-972e-e87f3f49a109.png)

Then you can do:

    left_sheet.column += right_sheet

**Comment by geeek987** [comment]
Thank you!
