### ISSUE TITLE
iget_records preserving order

### ISSUE THREAD

**Issue by stephen-bunn** [pyexcel/pyexcel#95]
Is there any current method of preserving the ordering of the data read in from `iget_records`?

Potentially a way to either specify the method to utilize ordered dicts instead of normal ones?
Or maybe a list parameter in `isave_as` / `save_as` which specifies the ordering that a list of normal dictionary records should be saved in.

**Comment by chfw** [comment]
No, currently I don't think I have paid attention to it. 

Yes, I can look at your suggestion. As a last resort, we could get a nominated list of column names to enforce the order.

**Comment by chfw** [comment]
Please try with:

    pip install https://github.com/pyexcel/pyexcel/archive/master.zip

By default the order is preserved as it returns an ordered dict. If custom order is required, please provide `customer_headers=['a', 'preferred', 'order']` to those functions.
