### ISSUE TITLE
Pivot Table 

### ISSUE THREAD

**Issue by geeek987** [pyexcel/pyexcel#96]
Hi, I have huge data so I am using Pivot Table on every sheet of my Excel. I have 25 sheets.The output of my Python program gets saved to each sheet of the Excel file using Book.save() in PyExcel. I run this program once a week.  Will my Excel formulas used in new columns, pivot table and charts be gone on every book.save operation? If yes then is there a convenient option?

**Comment by chfw** [comment]
YES, THEY will be GONE! 

The alternative is to save the output to a separate file with a different name. NEVER overwrite the original excel file.

**Comment by geeek987** [comment]
True but my program runs in loops over so saving it to new file is not feasible for me.

**Comment by chfw** [comment]
Too few infomation for me to suggest anything helpful. I definitely dont want you to lose data.
